// build.mjs — 将思源版 siyuan-diaryflow 构建为 Orca Note 插件
// 用法：node build.mjs
// 流程：拆分原 bundle 模块 → 应用 patches/ 补丁 → 拼接 Orca 入口 + CSS → 输出 dist/index.js

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC_DIR = "E:/Siyuan/One/data/plugins/siyuan-diaryflow";
const SRC = SRC_DIR + "/index.js";
const SRC_CSS = SRC_DIR + "/index.css";
const SRC_ICON = SRC_DIR + "/icon.png";

const bundle = readFileSync(SRC, "utf8");

// ---------- 模块拆分 ----------
const M = [
  "// src/storage.js",
  "// src/util.js",
  "// src/render.js",
  "// src/export.js",
  "// src/editor.js",
  "// src/index.js"
];
const at = M.map((m) => bundle.indexOf(m));
at.forEach((pos, i) => {
  if (pos < 0) {
    console.error("FATAL: module marker not found:", M[i]);
    process.exit(1);
  }
});

const header = bundle.slice(0, at[0]);
const blocks = {
  storage: bundle.slice(at[0], at[1]),
  util: bundle.slice(at[1], at[2]),
  render: bundle.slice(at[2], at[3]),
  export: bundle.slice(at[3], at[4]),
  editor: bundle.slice(at[4], at[5])
};

// ---------- 补丁 ----------
const patches = [
  { block: "render", name: "P01-icons-dict" },
  { block: "render", name: "P02-ico-use" },
  { block: "render", name: "P03-popupbtn" },
  { block: "render", name: "P04-pinbadge" },
  { block: "render", name: "P05-iconclose", all: true },
  { block: "editor", name: "P05-iconclose", all: true },
  { block: "util", name: "P06-esc" },
  { block: "editor", name: "P07-assetdir" },
  { block: "editor", name: "P08-upload" },
  { block: "editor", name: "P09-readdir" },
  { block: "editor", name: "P10-pickerbg" },
  { block: "editor", name: "P11-coversrc" },
  { block: "export", name: "P12-exportmd" },
  { block: "export", name: "P13-exportword" },
  { block: "editor", name: "P14-videolb" },
  { block: "editor", name: "P15-overlaybase" },
  { block: "render", name: "P16-rmresource" },
  { block: "storage", name: "P17-tags-storage" },
  { block: "editor", name: "P18-tags-editinit" },
  { block: "editor", name: "P19-tags-editinput" },
  { block: "editor", name: "P20-tags-editsave" },
  { block: "render", name: "P21-tags-html-fn" },
  { block: "render", name: "P22-tags-carddl" },
  { block: "render", name: "P23-tags-filter" },
  { block: "editor", name: "P24-tags-handle" },
  { block: "render", name: "P25-rmupload" },
  { block: "render", name: "P26-rmdelete" },
  { block: "render", name: "P27-empty-hint" },
  { block: "render", name: "P28-strip-text-html" },
  { block: "render", name: "P29-cover-cal-btn" },
  { block: "render", name: "P30-rm-sig-calendar" },
  { block: "render", name: "P31-fab-tag-filter" },
  { block: "render", name: "P32-ico-label" },
  { block: "editor", name: "P33-compose-multiimg" },
  { block: "render", name: "P34-md-link" },
  { block: "render", name: "P35-md-underline" },
  { block: "render", name: "P36-fab-title" },
  { block: "render", name: "P37-edit-title" },
  { block: "render", name: "P38-empty-orca" },
  { block: "render", name: "P39-md-dfref" },
  { block: "render", name: "P40-cover-sig" },
  { block: "render", name: "P41-hide-sig-below" },
  { block: "render", name: "P42-img-ninegrid" },
  { block: "render", name: "P43-md-lists" },
  { block: "render", name: "P44-actions-slim" },
  { block: "editor", name: "P45-cover-resolve" },
  { block: "editor", name: "P46-settings-media-save" },
  { block: "render", name: "P47-avatar-blank" },
  { block: "render", name: "P48-pin-firstline" },
  { block: "editor", name: "P49-avatar-image-robust" },
  { block: "render", name: "P50-cover-resolve-src" },
  { block: "editor", name: "P51-cover-upload-catch" },
  { block: "editor", name: "P52-avatar-accept" }
];

function applyPatch(block, name, all) {
  const find = readFileSync(join(ROOT, "patches", name + ".find.txt"), "utf8");
  const rep = readFileSync(join(ROOT, "patches", name + ".replace.txt"), "utf8");
  let s = blocks[block];
  const i = s.indexOf(find);
  if (i < 0) {
    console.error("PATCH FAILED:", block, name);
    process.exit(1);
  }
  if (!all && s.indexOf(find, i + 1) >= 0) {
    console.error("PATCH AMBIGUOUS:", block, name);
    process.exit(1);
  }
  if (all) {
    while (s.indexOf(find) >= 0) s = s.replace(find, rep);
  } else {
    s = s.slice(0, i) + rep + s.slice(i + find.length);
  }
  blocks[block] = s;
  console.log("patched:", block, name);
}

for (const p of patches) applyPatch(p.block, p.name, p.all);

// ---------- 残留检查 ----------
const leftovers = ["xlink:href", "api/file/", "window.siyuan", "ASSET_URL", "ASSET_DIR", "ensureAssetDir", "putFile"];
for (const [k, v] of Object.entries(blocks)) {
  for (const bad of leftovers) {
    if (v.includes(bad)) {
      console.error("LEFTOVER in", k, ":", bad);
      process.exit(1);
    }
  }
}
console.log("no siyuan leftovers in modules");

// ---------- CSS ----------
const css = readFileSync(SRC_CSS, "utf8");
const extraCss = [
  "",
  "/* ===== Orca Note + Apple HIG (appended by build.mjs) ===== */",
  ".orca-df-host {",
  "  flex: 1 1 auto;",
  "  align-self: stretch;",
  "  width: 100%;",
  "  min-width: 0;",
  "  height: 100%;",
  "  min-height: 0;",
  "  display: flex;",
  "  flex-direction: column;",
  "  overflow: hidden;",
  "}",
  ".orca-df-scope .mom-root { height: 100%; width: 100%; min-width: 0; }",
  "/* ---- Apple / iOS-macOS tokens → legacy --b3-* ---- */",
  ".orca-df-scope {",
  "  --df-font: -apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"SF Pro Display\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;",
  "  --df-font-mono: \"SF Mono\", ui-monospace, Menlo, Consolas, monospace;",
  "  --df-radius-sm: 6px;",
  "  --df-radius-md: 10px;",
  "  --df-radius-lg: 14px;",
  "  --df-radius-xl: 20px;",
  "  --df-radius-pill: 980px;",
  "  --df-stroke: 0.5px;",
  "  --df-shadow-4: 0 1px 2px rgba(0,0,0,.04), 0 2px 8px rgba(0,0,0,.06);",
  "  --df-shadow-8: 0 2px 8px rgba(0,0,0,.06), 0 8px 24px rgba(0,0,0,.08);",
  "  --df-shadow-16: 0 8px 28px rgba(0,0,0,.12), 0 2px 8px rgba(0,0,0,.04);",
  "  --df-brand: #007AFF;",
  "  --df-brand-hover: #0066D6;",
  "  --df-brand-pressed: #0055B3;",
  "  --df-brand-fg: #FFFFFF;",
  "  --df-brand-tint: rgba(0,122,255,.12);",
  "  --df-brand-tint-2: rgba(0,122,255,.20);",
  "  --df-fill-tertiary: rgba(120,120,128,.12);",
  "  --b3-theme-background: #F2F2F7;",
  "  --b3-theme-background-light: rgba(255,255,255,0.72);",
  "  --b3-theme-on-background: #000000;",
  "  --b3-theme-primary: var(--df-brand);",
  "  --b3-theme-primary-light: #5AC8FA;",
  "  --b3-theme-primary-lighter: var(--df-brand-tint-2);",
  "  --b3-theme-primary-lightest: var(--df-brand-tint);",
  "  --b3-theme-on-primary: var(--df-brand-fg);",
  "  --b3-border-color: rgba(60,60,67,0.18);",
  "  --b3-theme-surface: #FFFFFF;",
  "  --b3-theme-surface-lighter: #F2F2F7;",
  "  --b3-theme-on-surface: #000000;",
  "  --b3-theme-on-surface-light: #8E8E93;",
  "  --b3-list-hover: rgba(120,120,128,.12);",
  "  --b3-font-family-code: var(--df-font-mono);",
  "  --moments-card-border: rgba(60,60,67,0.12);",
  "  --moments-nav-border: rgba(60,60,67,0.18);",
  "  color: var(--b3-theme-on-background);",
  "  font-family: var(--df-font);",
  "  font-size: 15px;",
  "  line-height: 1.47;",
  "  letter-spacing: -0.01em;",
  "  -webkit-font-smoothing: antialiased;",
  "}",
  ".orca-df-scope.orca-df-dark {",
  "  --df-shadow-4: 0 1px 2px rgba(0,0,0,.35), 0 2px 8px rgba(0,0,0,.28);",
  "  --df-shadow-8: 0 2px 8px rgba(0,0,0,.4), 0 8px 24px rgba(0,0,0,.35);",
  "  --df-shadow-16: 0 8px 28px rgba(0,0,0,.55);",
  "  --df-brand: #0A84FF;",
  "  --df-brand-hover: #409CFF;",
  "  --df-brand-pressed: #0066CC;",
  "  --df-brand-fg: #FFFFFF;",
  "  --df-brand-tint: rgba(10,132,255,.22);",
  "  --df-brand-tint-2: rgba(10,132,255,.32);",
  "  --df-fill-tertiary: rgba(120,120,128,.24);",
  "  --b3-theme-background: #000000;",
  "  --b3-theme-background-light: rgba(44,44,46,0.78);",
  "  --b3-theme-on-background: #FFFFFF;",
  "  --b3-theme-primary: var(--df-brand);",
  "  --b3-theme-primary-light: #64D2FF;",
  "  --b3-theme-primary-lighter: var(--df-brand-tint-2);",
  "  --b3-theme-primary-lightest: var(--df-brand-tint);",
  "  --b3-theme-on-primary: var(--df-brand-fg);",
  "  --b3-border-color: rgba(84,84,88,0.65);",
  "  --b3-theme-surface: #1C1C1E;",
  "  --b3-theme-surface-lighter: #2C2C2E;",
  "  --b3-theme-on-surface: #FFFFFF;",
  "  --b3-theme-on-surface-light: #8E8E93;",
  "  --b3-list-hover: rgba(120,120,128,.24);",
  "  --moments-card-border: rgba(84,84,88,0.45);",
  "  --moments-nav-border: rgba(84,84,88,0.65);",
  "}",
  ".orca-df-hb-icon { display: inline-flex; align-items: center; justify-content: center; }",
  ".orca-df-hb-icon svg { display: block; }",
  "/* ---- Surfaces / cards ---- */",
  ".orca-df-scope .mom-root {",
  "  background: var(--b3-theme-background);",
  "  font-family: var(--df-font);",
  "}",
  ".orca-df-scope .mom-item,",
  ".orca-df-scope .north-luna-moments-item {",
  "  width: 100%;",
  "  max-width: none;",
  "  margin-left: 0;",
  "  margin-right: 0;",
  "  background: var(--b3-theme-surface);",
  "  border: var(--df-stroke) solid var(--moments-card-border);",
  "  border-radius: var(--df-radius-lg);",
  "  box-shadow: var(--df-shadow-4);",
  "  transition: transform .18s cubic-bezier(.22,.61,.36,1), box-shadow .18s ease, background .18s ease;",
  "}",
  ".orca-df-scope .mom-item:hover,",
  ".orca-df-scope .north-luna-moments-item:hover {",
  "  box-shadow: var(--df-shadow-8);",
  "}",
  ".orca-df-scope .mom-list {",
  "  align-items: stretch;",
  "  padding-left: 16px;",
  "  padding-right: 16px;",
  "  gap: 12px;",
  "}",
  ".orca-df-scope .mom-filter-bar,",
  ".orca-df-scope .mom-pin-strip { width: 100%; }",
  ".orca-df-scope .mom-avatar,",
  ".orca-df-scope .mom-avatar-ph {",
  "  border-radius: var(--df-radius-md);",
  "}",
  ".orca-df-scope .north-luna-moments-item-name {",
  "  font-weight: 600;",
  "  letter-spacing: -0.02em;",
  "}",
  "/* ---- Controls ---- */",
  ".orca-df-scope button,",
  ".orca-df-scope input,",
  ".orca-df-scope textarea,",
  ".orca-df-scope select {",
  "  font-family: inherit;",
  "}",
  ".orca-df-scope .mom-publish-submit,",
  ".orca-df-scope .mom-empty-btn,",
  ".orca-df-scope .mom-btn-primary {",
  "  height: 34px;",
  "  min-width: 72px;",
  "  padding: 0 16px;",
  "  border: none;",
  "  border-radius: var(--df-radius-pill);",
  "  background: var(--df-brand);",
  "  color: var(--df-brand-fg);",
  "  font-size: 15px;",
  "  font-weight: 600;",
  "  letter-spacing: -0.01em;",
  "  line-height: 1;",
  "  box-shadow: none;",
  "  transition: opacity .15s ease, transform .15s ease, background .15s ease;",
  "}",
  ".orca-df-scope .mom-publish-submit:hover,",
  ".orca-df-scope .mom-empty-btn:hover,",
  ".orca-df-scope .mom-btn-primary:hover {",
  "  background: var(--df-brand-hover);",
  "  opacity: 0.96;",
  "}",
  ".orca-df-scope .mom-publish-submit:active,",
  ".orca-df-scope .mom-empty-btn:active,",
  ".orca-df-scope .mom-btn-primary:active {",
  "  background: var(--df-brand-pressed);",
  "  opacity: 0.88;",
  "}",
  ".orca-df-scope .mom-publish-inp,",
  ".orca-df-scope .mom-publish-textarea {",
  "  border: none;",
  "  border-radius: var(--df-radius-md);",
  "  background: var(--df-fill-tertiary);",
  "  transition: background .15s ease, box-shadow .15s ease;",
  "}",
  ".orca-df-scope .mom-publish-inp:hover,",
  ".orca-df-scope .mom-publish-textarea:hover {",
  "  background: color-mix(in srgb, var(--df-fill-tertiary) 85%, var(--df-brand) 15%);",
  "}",
  ".orca-df-scope .mom-publish-inp:focus,",
  ".orca-df-scope .mom-publish-textarea:focus,",
  ".orca-df-scope .mom-publish-card--editor:focus-within {",
  "  outline: none;",
  "  box-shadow: 0 0 0 3px var(--df-brand-tint);",
  "  background: var(--b3-theme-surface);",
  "}",
  ".orca-df-scope .mom-publish-card {",
  "  background: var(--b3-theme-surface);",
  "  border: var(--df-stroke) solid var(--moments-card-border);",
  "  border-radius: var(--df-radius-lg);",
  "  box-shadow: var(--df-shadow-4);",
  "}",
  ".orca-df-scope .mom-publish-nav {",
  "  height: 52px;",
  "  border-bottom: var(--df-stroke) solid var(--moments-nav-border);",
  "  background: color-mix(in srgb, var(--b3-theme-surface) 72%, transparent);",
  "  backdrop-filter: saturate(180%) blur(20px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(20px);",
  "}",
  ".orca-df-scope .mom-publish-title {",
  "  font-size: 17px;",
  "  font-weight: 600;",
  "  letter-spacing: -0.02em;",
  "}",
  ".orca-df-scope .mom-publish-grid-add,",
  ".orca-df-scope .mom-publish-grid-prev {",
  "  border-radius: var(--df-radius-md);",
  "}",
  ".orca-df-scope .mom-fab-stack .mom-outline-fab,",
  ".orca-df-scope .mom-fab-stack .mom-tag-fab,",
  ".orca-df-scope .mom-fab,",
  ".orca-df-scope button.mom-outline-fab,",
  ".orca-df-scope button.mom-tag-fab {",
  "  width: 44px;",
  "  height: 44px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: color-mix(in srgb, var(--b3-theme-surface) 82%, transparent);",
  "  backdrop-filter: saturate(180%) blur(16px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(16px);",
  "  box-shadow: var(--df-shadow-8);",
  "  color: var(--df-brand);",
  "}",
  ".orca-df-scope .mom-fab-stack .mom-outline-fab:hover,",
  ".orca-df-scope .mom-fab-stack .mom-tag-fab:hover,",
  ".orca-df-scope .mom-fab:hover {",
  "  background: var(--b3-theme-surface);",
  "}",
  ".orca-df-scope .mom-tag-fab.is-on {",
  "  color: var(--df-brand-fg);",
  "  background: var(--df-brand);",
  "  border-color: transparent;",
  "}",
  ".orca-df-scope .mom-cover-default {",
  "  background:",
  "    linear-gradient(160deg, #5AC8FA 0%, #007AFF 48%, #5856D6 100%);",
  "}",
  ".orca-df-scope.orca-df-dark .mom-cover-default {",
  "  background:",
  "    linear-gradient(160deg, #64D2FF 0%, #0A84FF 45%, #5E5CE6 100%);",
  "}",
  ".orca-df-scope .mom-cover-actions .mom-cover-settings,",
  ".orca-df-scope .mom-cover-actions button {",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: rgba(255,255,255,.28);",
  "  backdrop-filter: saturate(180%) blur(16px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(16px);",
  "  color: #fff;",
  "}",
  "/* ---- Tags / chips ---- */",
  ".north-luna-moments-tags { display: flex; flex-wrap: wrap; gap: 6px 8px; margin-top: 10px; }",
  ".north-luna-moments-tag {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  color: var(--df-brand);",
  "  background: var(--df-brand-tint);",
  "  padding: 4px 10px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  cursor: pointer;",
  "  user-select: none;",
  "  transition: background .15s ease, opacity .15s ease;",
  "}",
  ".north-luna-moments-tag:hover { background: var(--df-brand-tint-2); }",
  ".mom-publish-info { flex-wrap: wrap; }",
  ".mom-publish-info .mom-publish-info-tags { flex: 1 1 100%; min-width: 0; margin-top: 4px; }",
  "/* ---- Empty ---- */",
  ".mom-empty { padding: 64px 28px 52px; text-align: center; }",
  ".mom-empty-ico { font-size: 48px; line-height: 1; margin-bottom: 14px; opacity: 0.9; }",
  ".mom-empty-title { font-size: 20px; font-weight: 700; letter-spacing: -0.03em; margin: 0 0 8px; color: var(--b3-theme-on-surface); }",
  ".mom-empty-sub { font-size: 15px; line-height: 1.5; margin: 0 0 6px; color: var(--b3-theme-on-surface-light); }",
  ".mom-empty-hint { font-size: 13px; line-height: 1.5; margin: 0 0 20px; color: var(--b3-theme-on-surface-light); opacity: 0.95; }",
  ".mom-empty-btn { margin-top: 4px; }",
  "/* ---- Tag bar / refs ---- */",
  ".orca-df-tagbar { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; padding: 10px 16px 0; width: 100%; box-sizing: border-box; }",
  ".orca-df-tagbar-label { font-size: 13px; color: var(--b3-theme-on-surface-light); margin-right: 2px; }",
  ".orca-df-tagchip {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 5px 12px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: var(--df-fill-tertiary);",
  "  color: var(--b3-theme-on-background);",
  "  cursor: pointer;",
  "}",
  ".orca-df-tagchip.is-on, .orca-df-tagchip:hover {",
  "  background: var(--df-brand-tint);",
  "  color: var(--df-brand);",
  "}",
  ".orca-df-refs { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }",
  ".orca-df-refchip {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 3px 10px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: var(--df-stroke) dashed var(--b3-border-color);",
  "  background: transparent;",
  "  color: var(--b3-theme-on-surface-light);",
  "  cursor: pointer;",
  "}",
  ".orca-df-refchip:hover { color: var(--df-brand); border-color: var(--df-brand); background: var(--df-brand-tint); }",
  ".orca-df-open-orca {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 5px 10px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: transparent;",
  "  color: var(--df-brand);",
  "  font-weight: 600;",
  "  cursor: pointer;",
  "}",
  ".orca-df-open-orca:hover { background: var(--df-brand-tint); }",
  ".orca-df-loc-btn.is-on { color: var(--df-brand); }",
  ".orca-df-tag-btn.is-on { color: var(--df-brand); }",
  ".orca-df-actions-wrap,",
  ".orca-df-scope .north-luna-moments-item-actions {",
  "  position: relative;",
  "}",
  ".orca-df-scope .north-luna-moments-action-bar {",
  "  display: flex;",
  "  align-items: center;",
  "  gap: 2px;",
  "  justify-content: flex-start;",
  "  flex-wrap: nowrap;",
  "}",
  ".orca-df-scope .north-luna-moments-action-btn {",
  "  width: 34px;",
  "  height: 34px;",
  "  border-radius: var(--df-radius-pill);",
  "}",
  ".orca-df-more-inline {",
  "  display: none;",
  "  align-items: center;",
  "  gap: 2px;",
  "  margin-left: 2px;",
  "  padding-left: 4px;",
  "  border-left: var(--df-stroke) solid color-mix(in srgb, var(--b3-border-color) 80%, transparent);",
  "  animation: orca-df-more-in .16s ease;",
  "}",
  ".north-luna-moments-action-bar.is-more-open .orca-df-more-inline,",
  ".mom-action-bar.is-more-open .orca-df-more-inline {",
  "  display: inline-flex;",
  "}",
  ".north-luna-moments-action-bar.is-more-open .orca-df-more-btn,",
  ".mom-action-bar.is-more-open .orca-df-more-btn {",
  "  color: var(--df-brand);",
  "  background: var(--df-brand-tint);",
  "}",
  ".orca-df-more-inline .orca-df-more-del {",
  "  color: #FF3B30;",
  "}",
  ".orca-df-more-inline .orca-df-more-del:hover {",
  "  background: rgba(255,59,48,.1);",
  "}",
  "@keyframes orca-df-more-in {",
  "  from { opacity: 0; transform: translateX(-4px); }",
  "  to { opacity: 1; transform: translateX(0); }",
  "}",
  ".orca-df-tags-list {",
  "  display: flex;",
  "  flex-wrap: wrap;",
  "  gap: 8px;",
  "  max-height: 220px;",
  "  overflow-y: auto;",
  "  margin-bottom: 12px;",
  "}",
  ".orca-df-tags-empty {",
  "  font-size: 13px;",
  "  color: var(--b3-theme-on-surface-light);",
  "  padding: 8px 0;",
  "}",
  ".orca-df-tagpick {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 4px 12px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: var(--df-stroke) solid var(--b3-border-color);",
  "  background: var(--df-fill-tertiary);",
  "  color: var(--b3-theme-on-background);",
  "  cursor: pointer;",
  "}",
  ".orca-df-tagpick.is-on {",
  "  background: var(--df-brand-tint);",
  "  color: var(--df-brand);",
  "  border-color: var(--df-brand);",
  "}",
  ".orca-df-tags-add {",
  "  display: flex;",
  "  gap: 8px;",
  "  align-items: center;",
  "  margin-bottom: 8px;",
  "}",
  ".orca-df-tags-add .mom-inp { flex: 1 1 auto; min-width: 0; }",
  ".orca-df-loc-meta {",
  "  cursor: pointer;",
  "  color: var(--b3-theme-on-surface-light);",
  "}",
  ".orca-df-loc-meta:hover { color: var(--df-brand); }",
  ".orca-df-loc-pin { font-size: 12px; }",
  ".mom-publish-orca {",
  "  flex: none;",
  "  height: 34px;",
  "  padding: 0 14px;",
  "  margin-right: 0;",
  "  border: none;",
  "  border-radius: var(--df-radius-pill);",
  "  background: var(--df-fill-tertiary);",
  "  color: var(--df-brand);",
  "  font-size: 13px;",
  "  font-weight: 600;",
  "  cursor: pointer;",
  "}",
  ".mom-publish-orca:hover {",
  "  background: var(--df-brand-tint);",
  "}",
  ".mom-publish-nav-right { display: flex; align-items: center; gap: 8px; margin-left: auto; position: relative; z-index: 2; }",
  ".mom-publish-nav .mom-publish-back { position: relative; z-index: 2; border-radius: var(--df-radius-pill); color: var(--df-brand); }",
  ".mom-publish-nav .mom-publish-title { pointer-events: none; z-index: 0; }",
  "/* ---- Cover actions ---- */",
  ".mom-cover-actions {",
  "  position: absolute;",
  "  top: 14px;",
  "  right: 14px;",
  "  z-index: 12;",
  "  display: flex;",
  "  align-items: center;",
  "  gap: 8px;",
  "}",
  ".mom-cover-actions .mom-cover-settings {",
  "  position: static;",
  "  top: auto;",
  "  right: auto;",
  "}",
  ".mom-cover-signature {",
  "  position: absolute;",
  "  left: 16px;",
  "  right: 120px;",
  "  bottom: 22px;",
  "  z-index: 11;",
  "  margin: 0;",
  "  font-size: 15px;",
  "  line-height: 1.45;",
  "  font-weight: 500;",
  "  letter-spacing: 0.06em;",
  "  color: #fff;",
  "  text-shadow: 0 1px 2px rgba(0,0,0,.5), 0 2px 12px rgba(0,0,0,.35);",
  "  pointer-events: none;",
  "  white-space: nowrap;",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "}",
  ".north-luna-moments-image-grid.nine {",
  "  grid-template-columns: repeat(3, 1fr);",
  "  max-width: 300px;",
  "}",
  ".north-luna-moments-grid-more {",
  "  position: relative;",
  "  display: block;",
  "  overflow: hidden;",
  "  border-radius: inherit;",
  "  cursor: pointer;",
  "}",
  ".north-luna-moments-grid-more .north-luna-moments-grid-img,",
  ".north-luna-moments-grid-more .north-luna-moments-grid-video-el {",
  "  width: 100%;",
  "  height: 100%;",
  "  object-fit: cover;",
  "  display: block;",
  "}",
  ".north-luna-moments-grid-more-badge {",
  "  position: absolute;",
  "  inset: 0;",
  "  display: flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  background: rgba(0,0,0,.46);",
  "  color: #fff;",
  "  font-size: 22px;",
  "  font-weight: 600;",
  "  letter-spacing: 0.02em;",
  "  pointer-events: none;",
  "  text-shadow: 0 1px 2px rgba(0,0,0,.35);",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ul,",
  ".north-luna-moments-item-text .orca-df-md-ol {",
  "  margin: 4px 0 6px;",
  "  padding-left: 1.4em;",
  "  list-style-position: outside;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ul {",
  "  list-style-type: disc !important;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ol {",
  "  list-style-type: decimal !important;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ul .orca-df-md-ul { list-style-type: circle !important; }",
  ".north-luna-moments-item-text .orca-df-md-ul .orca-df-md-ul .orca-df-md-ul { list-style-type: square !important; }",
  ".north-luna-moments-item-text .orca-df-md-li {",
  "  margin: 2px 0;",
  "  line-height: 1.55;",
  "  display: list-item !important;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-p {",
  "  margin: 0 0 4px;",
  "  line-height: 1.55;",
  "  white-space: pre-wrap;",
  "  word-break: break-word;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-gap { height: 8px; }",
  ".north-luna-moments-item-text .orca-df-md-h {",
  "  font-weight: 650;",
  "  margin: 6px 0 4px;",
  "  line-height: 1.4;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-h1 { font-size: 1.2em; }",
  ".north-luna-moments-item-text .orca-df-md-h2 { font-size: 1.1em; }",
  ".north-luna-moments-item-text .orca-df-md-h3 { font-size: 1.05em; }",
  ".north-luna-moments-item-text .orca-df-md-quote {",
  "  margin: 4px 0;",
  "  padding: 2px 0 2px 10px;",
  "  border-left: 3px solid var(--b3-border-color);",
  "  color: var(--b3-theme-on-surface-light);",
  "}",
  ".north-luna-moments-item-text .orca-df-md-code {",
  "  margin: 6px 0;",
  "  padding: 8px 10px;",
  "  border-radius: 8px;",
  "  background: var(--df-fill-tertiary);",
  "  overflow: auto;",
  "  font-size: 13px;",
  "  line-height: 1.45;",
  "}",
  "/* ---- Popover ---- */",
  ".orca-df-tag-popover {",
  "  position: fixed;",
  "  z-index: 2147483001;",
  "  min-width: 180px;",
  "  max-width: min(280px, calc(100vw - 24px));",
  "  max-height: min(360px, 50vh);",
  "  overflow: auto;",
  "  padding: 6px;",
  "  border-radius: var(--df-radius-lg);",
  "  background: color-mix(in srgb, var(--b3-theme-surface) 86%, transparent);",
  "  border: var(--df-stroke) solid var(--moments-card-border);",
  "  box-shadow: var(--df-shadow-16);",
  "  backdrop-filter: saturate(180%) blur(24px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(24px);",
  "  box-sizing: border-box;",
  "}",
  ".orca-df-tag-popover-title {",
  "  font-size: 12px;",
  "  font-weight: 600;",
  "  color: var(--b3-theme-on-surface-light);",
  "  padding: 8px 10px 6px;",
  "  text-transform: uppercase;",
  "  letter-spacing: 0.04em;",
  "}",
  ".orca-df-tag-popover-item {",
  "  display: block;",
  "  width: 100%;",
  "  text-align: left;",
  "  border: none;",
  "  background: transparent;",
  "  color: var(--b3-theme-on-background);",
  "  font-size: 15px;",
  "  line-height: 1.35;",
  "  padding: 10px 12px;",
  "  border-radius: var(--df-radius-md);",
  "  cursor: pointer;",
  "}",
  ".orca-df-tag-popover-item:hover,",
  ".orca-df-tag-popover-item.is-on {",
  "  background: var(--df-brand-tint);",
  "  color: var(--df-brand);",
  "}",
  ".orca-df-tag-popover-empty {",
  "  font-size: 13px;",
  "  color: var(--b3-theme-on-surface-light);",
  "  padding: 12px 10px;",
  "}",
  "/* ---- Motion ---- */",
  "@media (prefers-reduced-motion: no-preference) {",
  "  .orca-df-scope .mom-item,",
  "  .orca-df-scope .north-luna-moments-item,",
  "  .orca-df-scope .mom-publish-submit,",
  "  .orca-df-scope .orca-df-tagchip,",
  "  .orca-df-scope .mom-outline-fab,",
  "  .orca-df-scope .mom-tag-fab {",
  "    transition: background .18s cubic-bezier(.22,.61,.36,1), border-color .18s ease, box-shadow .18s ease, color .18s ease, transform .18s cubic-bezier(.22,.61,.36,1), opacity .15s ease;",
  "  }",
  "  .orca-df-scope .mom-outline-fab:active,",
  "  .orca-df-scope .mom-tag-fab:active,",
  "  .orca-df-scope .mom-publish-submit:active {",
  "    transform: scale(0.96);",
  "  }",
  "}",
  "/* ---- 正文观感仍对齐虎鲸字号变量 ---- */",
  ".orca-df-scope {",
  "  --moments-text: var(--orca-color-text-1, var(--b3-theme-on-background, #000));",
  "  --df-body-font: var(--orca-fontfamily-ui, var(--orca-font-family, var(--df-font)));",
  "  --df-body-size: var(--orca-fontsize, 15px);",
  "  --df-body-leading: var(--orca-block-line-height, var(--orca-lineheight-md, 1.47));",
  "}",
  ".orca-df-scope .north-luna-moments-item-text,",
  ".orca-df-scope .mom-publish-textarea,",
  ".orca-df-scope .mom-publish-card--editor .mom-publish-textarea {",
  "  font-family: var(--df-body-font);",
  "  font-size: var(--df-body-size);",
  "  line-height: var(--df-body-leading);",
  "  color: var(--moments-text);",
  "  letter-spacing: -0.01em;",
  "  font-weight: 400;",
  "}",
  ".orca-df-scope .north-luna-moments-no-text {",
  "  color: var(--orca-color-text-3, var(--b3-theme-on-surface-light, #8E8E93));",
  "  font-size: var(--df-body-size);",
  "  line-height: var(--df-body-leading);",
  "}",
  ".orca-df-scope .mom-inline-code,",
  ".orca-df-scope .north-luna-moments-item-text code {",
  "  font-family: var(--orca-fontfamily-code, var(--df-font-mono));",
  "  font-size: 0.92em;",
  "  line-height: inherit;",
  "  background: var(--df-fill-tertiary);",
  "  border-radius: 4px;",
  "  padding: 0.1em 0.35em;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text a,",
  ".orca-df-scope .north-luna-moments-item-text .mom-md-link {",
  "  color: var(--orca-color-primary-5, var(--df-brand));",
  "}",
  "/* ---- 卡片正文层级：正文 > 列表 > meta 日期 ---- */",
  ".orca-df-scope .mom-item,",
  ".orca-df-scope .north-luna-moments-item {",
  "  padding: 12px 14px 10px;",
  "}",
  ".orca-df-scope .north-luna-moments-item-header {",
  "  margin-bottom: 6px;",
  "  gap: 8px;",
  "}",
  ".orca-df-scope .north-luna-moments-item-header .mom-avatar,",
  ".orca-df-scope .north-luna-moments-item-header .mom-avatar-ph {",
  "  width: 34px;",
  "  height: 34px;",
  "  font-size: 14px;",
  "}",
  ".orca-df-scope .north-luna-moments-item-name {",
  "  font-size: 14px;",
  "  font-weight: 600;",
  "  color: var(--orca-color-text-2, var(--b3-theme-on-surface, #3A3A3C));",
  "}",
  ".orca-df-scope .north-luna-moments-item-text {",
  "  margin-bottom: 2px;",
  "  line-height: 1.55;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text > .orca-df-md-p:first-child {",
  "  color: var(--moments-text);",
  "  font-weight: 450;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-ul,",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-ol {",
  "  margin: 6px 0 2px;",
  "  color: color-mix(in srgb, var(--moments-text) 86%, transparent);",
  "  font-size: 0.96em;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-li {",
  "  line-height: 1.5;",
  "  margin: 1px 0;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-p + .orca-df-md-ul,",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-p + .orca-df-md-ol {",
  "  margin-top: 4px;",
  "}",
  ".orca-df-scope .north-luna-moments-tags {",
  "  margin-top: 6px;",
  "  margin-bottom: 0;",
  "}",
  ".orca-df-scope .north-luna-moments-item-meta {",
  "  margin-top: 8px;",
  "  margin-bottom: 0;",
  "}",
  ".orca-df-scope .north-luna-moments-meta-item {",
  "  font-size: 11px;",
  "  line-height: 1.35;",
  "  letter-spacing: 0.01em;",
  "  color: var(--orca-color-text-3, var(--b3-theme-on-surface-light, #8E8E93));",
  "  opacity: 0.92;",
  "}",
  ".orca-df-scope .north-luna-moments-meta-item + .north-luna-moments-meta-item::before {",
  "  margin: 0 6px;",
  "  opacity: 0.35;",
  "  font-weight: 500;",
  "}",
  ".orca-df-scope .north-luna-moments-item-actions {",
  "  margin-top: 4px;",
  "}",
  ".orca-df-scope .north-luna-moments-comment-panel {",
  "  margin-top: 6px;",
  "}",
  ".orca-df-scope .orca-df-inline-ref {",
  "  display: inline;",
  "  text-decoration: none;",
  "  border-bottom: 1px dashed color-mix(in srgb, var(--df-brand, #007AFF) 55%, transparent);",
  "  cursor: pointer;",
  "}",
  ".orca-df-scope .orca-df-inline-ref:hover {",
  "  border-bottom-style: solid;",
  "}",
  ".orca-df-refresh-fab svg { display: block; }",
  ".orca-df-time-hint {",
  "  margin: 10px 0 0;",
  "  font-size: 12px;",
  "  line-height: 1.4;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "}"
].join("\n");
const allCss = css + extraCss;

// ---------- 组装输出 ----------
const orcaBlocks = readFileSync(join(ROOT, "src", "orca-blocks.js"), "utf8");
const entry = readFileSync(join(ROOT, "src", "orca-entry.js"), "utf8");

const out = [
  "// orca-diaryflow v0.2.1 — light compose + Orca blocks (plan C)",
  "// Orca Note adaptation: panel, plugin-file media, block store, tags/refs/search",
  header,
  blocks.storage,
  blocks.util,
  blocks.render,
  blocks.export,
  blocks.editor,
  "",
  "// ===== Orca blocks store =====",
  orcaBlocks,
  "",
  "// ===== Orca Note entry =====",
  "var ORCA_CSS = " + JSON.stringify(allCss) + ";",
  "",
  entry
].join("\n");

mkdirSync(join(ROOT, "dist"), { recursive: true });
writeFileSync(join(ROOT, "dist", "index.js"), out);
// 集市图标：优先保留本地 icon-market.png（≤80）/ icon.png，勿被思源源图覆盖；SVG 单独保留
const marketIcon = join(ROOT, "icon-market.png");
if (existsSync(marketIcon)) {
  copyFileSync(marketIcon, join(ROOT, "icon.png"));
} else if (!existsSync(join(ROOT, "icon.png"))) {
  copyFileSync(SRC_ICON, join(ROOT, "icon.png"));
}

const VERSION = "0.3.2";
const REPO_URL = "https://github.com/kx1356/orca-diaryflow";

// plugin.json（mreader 同款格式；文件夹名仍为 orca-diaryflow）
const pluginMeta = {
  name: "orca-diaryflow",
  author: "kx1356",
  url: REPO_URL,
  version: VERSION,
  minAppVersion: "2.10.0",
  script: "index.js",
  description: {
    default: "Moments-style diary feed for Orca Note journals tagged #日记流",
    zh_CN: "日记流：朋友圈式时间线，深度编辑跳转虎鲸"
  },
  displayName: {
    default: "日记流",
    zh_CN: "日记流"
  },
  icon: "icon.png",
  backends: [],
  i18n: ["zh_CN", "en_US"]
};
writeFileSync(join(ROOT, "plugin.json"), JSON.stringify(pluginMeta, null, 4) + "\n");

// package.json（集市校验所需元数据）
const pkgMeta = {
  name: "orca-plugin-diaryflow",
  version: VERSION,
  type: "module",
  description:
    "Moments-style diary feed for Orca Note: timeline of #日记流 blocks, cover/avatar, tags, location, and deep edit in Orca journals.",
  author: "kx1356",
  license: "MIT",
  keywords: ["orca-note", "orca-plugin", "diary", "moments", "journal", "timeline"],
  repository: { type: "git", url: REPO_URL + ".git" },
  homepage: REPO_URL,
  bugs: { url: REPO_URL + "/issues" },
  private: false,
  scripts: {
    build: "node build.mjs",
    deploy: "node tools/deploy.mjs",
    "validate:marketplace": "node scripts/validate-marketplace-package.mjs"
  },
  orcaNoteMarketplace: {
    id: "orca-diaryflow",
    name: "日记流",
    category: "Productivity",
    artifactName: "orca-diaryflow",
    translations: {
      zh: {
        name: "日记流",
        description:
          "朋友圈式日记时间流：展示带 #日记流 标签的日记块，支持封面/头像、标签筛选、地点、置顶与评论；新建与深度编辑跳转虎鲸日记页。",
        category: "效率工具"
      },
      en: {
        name: "Diary Flow",
        description:
          "Moments-style diary feed: timeline of #日记流 journal blocks with cover/avatar, tags, location, pin and comments.",
        category: "Productivity"
      }
    }
  },
  peerDependencies: {
    react: "^18.2.0",
    valtio: "^1.13.2"
  }
};
writeFileSync(join(ROOT, "package.json"), JSON.stringify(pkgMeta, null, 2) + "\n");

console.log("built dist/index.js:", out.length, "bytes");
console.log("dist ready at", join(ROOT, "dist", "index.js"));
