// build.mjs — 将思源版 siyuan-diaryflow 构建为 Orca Note 插件
// 用法：node build.mjs
// 流程：拆分原 bundle 模块 → 应用 patches/ 补丁 → 拼接 Orca 入口 + CSS → 输出 dist/index.js

import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = dirname(fileURLToPath(import.meta.url));
// 可复现：默认 vendor/siyuan-diaryflow；可用环境变量覆盖（本机思源路径）
const SRC_DIR =
  process.env.SIYUAN_DIARYFLOW_SRC ||
  join(ROOT, "vendor", "siyuan-diaryflow");
const SRC = join(SRC_DIR, "index.js");
const SRC_CSS = join(SRC_DIR, "index.css");
const SRC_ICON = join(SRC_DIR, "icon.png");

if (!existsSync(SRC)) {
  console.error("FATAL: SiYuan Moments source not found:", SRC);
  console.error("Place a snapshot under vendor/siyuan-diaryflow/ or set SIYUAN_DIARYFLOW_SRC");
  process.exit(1);
}

const bundle = readFileSync(SRC, "utf8");

// ---------- 模块拆分 ----------
const M = [
  "// src/storage.js",
  "// src/util.js",
  "// src/render.js",
  "// src/export.js",
  "// src/editor.js",
  "// src/index.js"
];
const at = M.map((m) => bundle.indexOf(m));
at.forEach((pos, i) => {
  if (pos < 0) {
    console.error("FATAL: module marker not found:", M[i]);
    process.exit(1);
  }
});

const header = bundle.slice(0, at[0]);
const blocks = {
  storage: bundle.slice(at[0], at[1]),
  util: bundle.slice(at[1], at[2]),
  render: bundle.slice(at[2], at[3]),
  export: bundle.slice(at[3], at[4]),
  editor: bundle.slice(at[4], at[5])
};

// ---------- 补丁 ----------
const patches = [
  { block: "render", name: "P01-icons-dict" },
  { block: "render", name: "P02-ico-use" },
  { block: "render", name: "P03-popupbtn" },
  { block: "render", name: "P04-pinbadge" },
  { block: "render", name: "P05-iconclose", all: true },
  { block: "editor", name: "P05-iconclose", all: true },
  // P06 已废弃：esc 保持纯 HTML escape，资源解析只在 img/cover 路径做
  { block: "editor", name: "P07-assetdir" },
  { block: "editor", name: "P08-upload" },
  { block: "editor", name: "P09-readdir" },
  { block: "editor", name: "P10-pickerbg" },
  { block: "editor", name: "P11-coversrc" },
  { block: "export", name: "P12-exportmd" },
  { block: "export", name: "P13-exportword" },
  { block: "editor", name: "P14-videolb" },
  { block: "editor", name: "P15-overlaybase" },
  { block: "render", name: "P16-rmresource" },
  { block: "storage", name: "P17-tags-storage" },
  { block: "editor", name: "P18-tags-editinit" },
  { block: "editor", name: "P19-tags-editinput" },
  { block: "editor", name: "P20-tags-editsave" },
  { block: "render", name: "P21-tags-html-fn" },
  { block: "render", name: "P22-tags-carddl" },
  { block: "render", name: "P23-tags-filter" },
  { block: "editor", name: "P24-tags-handle" },
  { block: "render", name: "P25-rmupload" },
  { block: "render", name: "P26-rmdelete" },
  { block: "render", name: "P27-empty-hint" },
  { block: "render", name: "P28-strip-text-html" },
  { block: "render", name: "P29-cover-cal-btn" },
  { block: "render", name: "P30-rm-sig-calendar" },
  { block: "render", name: "P31-fab-tag-filter" },
  { block: "render", name: "P32-ico-label" },
  { block: "editor", name: "P33-compose-multiimg" },
  { block: "render", name: "P34-md-link" },
  { block: "render", name: "P35-md-underline" },
  { block: "render", name: "P36-fab-title" },
  { block: "render", name: "P37-edit-title" },
  { block: "render", name: "P38-empty-orca" },
  { block: "render", name: "P39-md-dfref" },
  { block: "render", name: "P40-cover-sig" },
  { block: "render", name: "P41-hide-sig-below" },
  { block: "render", name: "P42-img-ninegrid" },
  { block: "render", name: "P43-md-lists" },
  { block: "render", name: "P44-actions-slim" },
  { block: "editor", name: "P45-cover-resolve" },
  { block: "editor", name: "P46-settings-media-save" },
  { block: "render", name: "P47-avatar-blank" },
  { block: "render", name: "P48-pin-firstline" },
  { block: "editor", name: "P49-avatar-image-robust" },
  { block: "render", name: "P50-cover-resolve-src" },
  { block: "editor", name: "P51-cover-upload-catch" },
  { block: "editor", name: "P52-avatar-accept" },
  { block: "render", name: "P53-md-color-escape" },
  { block: "editor", name: "P54-heat-two-row" },
  { block: "editor", name: "P55-heat-narrow" },
  { block: "editor", name: "P56-settings-rm-export" },
  { block: "editor", name: "P57-settings-title" },
  { block: "editor", name: "P58-settings-rm-export-handler" },
  { block: "editor", name: "P59-cal-months", all: true },
  { block: "editor", name: "P60-cal-tip-photo" },
  { block: "editor", name: "P61-cal-tip-heat" },
  { block: "editor", name: "P62-cal-month-title" },
  { block: "editor", name: "P63-cal-header" },
  { block: "editor", name: "P64-cal-year-option" },
  { block: "editor", name: "P65-cal-target-title" },
  { block: "editor", name: "P66-cal-count" },
  { block: "editor", name: "P67-cal-heat-halves" },
  { block: "editor", name: "P68-cal-heat-empty" }
];

function applyPatch(block, name, all) {
  const find = readFileSync(join(ROOT, "patches", name + ".find.txt"), "utf8");
  const rep = readFileSync(join(ROOT, "patches", name + ".replace.txt"), "utf8");
  let s = blocks[block];
  const i = s.indexOf(find);
  if (i < 0) {
    console.error("PATCH FAILED:", block, name);
    process.exit(1);
  }
  if (!all && s.indexOf(find, i + 1) >= 0) {
    console.error("PATCH AMBIGUOUS:", block, name);
    process.exit(1);
  }
  if (all) {
    while (s.indexOf(find) >= 0) s = s.replace(find, rep);
  } else {
    s = s.slice(0, i) + rep + s.slice(i + find.length);
  }
  blocks[block] = s;
  console.log("patched:", block, name);
}

for (const p of patches) applyPatch(p.block, p.name, p.all);

// ---------- 残留检查 ----------
const leftovers = ["xlink:href", "api/file/", "window.siyuan", "ASSET_URL", "ASSET_DIR", "ensureAssetDir", "putFile"];
for (const [k, v] of Object.entries(blocks)) {
  for (const bad of leftovers) {
    if (v.includes(bad)) {
      console.error("LEFTOVER in", k, ":", bad);
      process.exit(1);
    }
  }
}
console.log("no siyuan leftovers in modules");

// ---------- CSS ----------
const css = readFileSync(SRC_CSS, "utf8");
const extraCss = [
  "",
  "/* ===== Orca Note + Apple HIG (appended by build.mjs) ===== */",
  ".orca-df-host {",
  "  flex: 1 1 auto;",
  "  align-self: stretch;",
  "  width: 100%;",
  "  min-width: 0;",
  "  height: 100%;",
  "  min-height: 0;",
  "  display: flex;",
  "  flex-direction: column;",
  "  overflow: hidden;",
  "}",
  ".orca-df-scope .mom-root { height: 100%; width: 100%; min-width: 0; }",
  "/* ---- Apple / iOS-macOS tokens → legacy --b3-* ---- */",
  ".orca-df-scope {",
  "  --df-font: -apple-system, BlinkMacSystemFont, \"SF Pro Text\", \"SF Pro Display\", \"Helvetica Neue\", Helvetica, Arial, sans-serif;",
  "  --df-font-mono: \"SF Mono\", ui-monospace, Menlo, Consolas, monospace;",
  "  --df-radius-sm: 6px;",
  "  --df-radius-md: 10px;",
  "  --df-radius-lg: 14px;",
  "  --df-radius-xl: 20px;",
  "  --df-radius-pill: 980px;",
  "  --df-stroke: 0.5px;",
  "  --df-shadow-4: 0 1px 2px rgba(0,0,0,.04), 0 2px 8px rgba(0,0,0,.06);",
  "  --df-shadow-8: 0 2px 8px rgba(0,0,0,.06), 0 8px 24px rgba(0,0,0,.08);",
  "  --df-shadow-16: 0 8px 28px rgba(0,0,0,.12), 0 2px 8px rgba(0,0,0,.04);",
  "  --df-brand: #007AFF;",
  "  --df-brand-hover: #0066D6;",
  "  --df-brand-pressed: #0055B3;",
  "  --df-brand-fg: #FFFFFF;",
  "  --df-brand-tint: rgba(0,122,255,.12);",
  "  --df-brand-tint-2: rgba(0,122,255,.20);",
  "  --df-fill-tertiary: rgba(120,120,128,.12);",
  "  --b3-theme-background: #F2F2F7;",
  "  --b3-theme-background-light: rgba(255,255,255,0.72);",
  "  --b3-theme-on-background: #000000;",
  "  --b3-theme-primary: var(--df-brand);",
  "  --b3-theme-primary-light: #5AC8FA;",
  "  --b3-theme-primary-lighter: var(--df-brand-tint-2);",
  "  --b3-theme-primary-lightest: var(--df-brand-tint);",
  "  --b3-theme-on-primary: var(--df-brand-fg);",
  "  --b3-border-color: rgba(60,60,67,0.18);",
  "  --b3-theme-surface: #FFFFFF;",
  "  --b3-theme-surface-lighter: #F2F2F7;",
  "  --b3-theme-on-surface: #000000;",
  "  --b3-theme-on-surface-light: #8E8E93;",
  "  --b3-list-hover: rgba(120,120,128,.12);",
  "  --b3-font-family-code: var(--df-font-mono);",
  "  --moments-card-border: rgba(60,60,67,0.12);",
  "  --moments-nav-border: rgba(60,60,67,0.18);",
  "  color: var(--b3-theme-on-background);",
  "  font-family: var(--df-font);",
  "  font-size: 15px;",
  "  line-height: 1.47;",
  "  letter-spacing: -0.01em;",
  "  -webkit-font-smoothing: antialiased;",
  "}",
  ".orca-df-scope.orca-df-dark {",
  "  --df-shadow-4: 0 1px 2px rgba(0,0,0,.35), 0 2px 8px rgba(0,0,0,.28);",
  "  --df-shadow-8: 0 2px 8px rgba(0,0,0,.4), 0 8px 24px rgba(0,0,0,.35);",
  "  --df-shadow-16: 0 8px 28px rgba(0,0,0,.55);",
  "  --df-brand: #0A84FF;",
  "  --df-brand-hover: #409CFF;",
  "  --df-brand-pressed: #0066CC;",
  "  --df-brand-fg: #FFFFFF;",
  "  --df-brand-tint: rgba(10,132,255,.22);",
  "  --df-brand-tint-2: rgba(10,132,255,.32);",
  "  --df-fill-tertiary: rgba(120,120,128,.24);",
  "  --b3-theme-background: #000000;",
  "  --b3-theme-background-light: rgba(44,44,46,0.78);",
  "  --b3-theme-on-background: #FFFFFF;",
  "  --b3-theme-primary: var(--df-brand);",
  "  --b3-theme-primary-light: #64D2FF;",
  "  --b3-theme-primary-lighter: var(--df-brand-tint-2);",
  "  --b3-theme-primary-lightest: var(--df-brand-tint);",
  "  --b3-theme-on-primary: var(--df-brand-fg);",
  "  --b3-border-color: rgba(84,84,88,0.65);",
  "  --b3-theme-surface: #1C1C1E;",
  "  --b3-theme-surface-lighter: #2C2C2E;",
  "  --b3-theme-on-surface: #FFFFFF;",
  "  --b3-theme-on-surface-light: #8E8E93;",
  "  --b3-list-hover: rgba(120,120,128,.24);",
  "  --moments-card-border: rgba(84,84,88,0.45);",
  "  --moments-nav-border: rgba(84,84,88,0.65);",
  "}",
  ".orca-df-hb-icon { display: inline-flex; align-items: center; justify-content: center; }",
  ".orca-df-hb-icon svg { display: block; }",
  "/* ---- Surfaces / cards ---- */",
  ".orca-df-scope .mom-root {",
  "  background: var(--b3-theme-background);",
  "  font-family: var(--df-font);",
  "}",
  ".orca-df-scope .mom-item,",
  ".orca-df-scope .north-luna-moments-item {",
  "  width: 100%;",
  "  max-width: none;",
  "  margin-left: 0;",
  "  margin-right: 0;",
  "  background: var(--b3-theme-surface);",
  "  border: var(--df-stroke) solid var(--moments-card-border);",
  "  border-radius: var(--df-radius-lg);",
  "  box-shadow: var(--df-shadow-4);",
  "  transition: transform .18s cubic-bezier(.22,.61,.36,1), box-shadow .18s ease, background .18s ease;",
  "}",
  ".orca-df-scope .mom-item:hover,",
  ".orca-df-scope .north-luna-moments-item:hover {",
  "  box-shadow: var(--df-shadow-8);",
  "}",
  ".orca-df-scope .mom-list {",
  "  align-items: stretch;",
  "  padding-left: 16px;",
  "  padding-right: 16px;",
  "  gap: 12px;",
  "}",
  ".orca-df-scope .mom-filter-bar { width: 100%; }",
  /* 置顶条：对齐标签栏——横排标签 + 芯片，去掉竖排字与大方块 */
  ".orca-df-scope .mom-pin-strip {",
  "  display: flex;",
  "  flex-wrap: wrap;",
  "  align-items: center;",
  "  gap: 8px;",
  "  width: 100%;",
  "  margin: 0;",
  "  padding: 10px 16px 0;",
  "  box-sizing: border-box;",
  "  background: transparent;",
  "  border: none;",
  "  border-radius: 0;",
  "  cursor: default;",
  "}",
  ".orca-df-scope .mom-pin-strip-label {",
  "  writing-mode: horizontal-tb;",
  "  white-space: nowrap;",
  "  font-size: 13px;",
  "  font-weight: 400;",
  "  line-height: 1;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "  margin-right: 2px;",
  "}",
  ".orca-df-scope .mom-pin-strip-thumbs {",
  "  display: flex;",
  "  flex-wrap: wrap;",
  "  align-items: center;",
  "  gap: 8px;",
  "  flex: 1 1 auto;",
  "  min-width: 0;",
  "  overflow: visible;",
  "}",
  ".orca-df-scope .mom-pin-group-text {",
  "  display: inline-flex !important;",
  "  align-items: center;",
  "  gap: 6px;",
  "  max-width: min(100%, 320px);",
  "  height: 32px;",
  "  padding: 0 12px 0 10px;",
  "  border-radius: 8px;",
  "  border: 1px solid color-mix(in srgb, var(--df-brand, #007AFF) 22%, transparent);",
  "  background: color-mix(in srgb, var(--df-brand, #007AFF) 8%, var(--orca-color-bg-1, #fff));",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "  grid-template-columns: none !important;",
  "}",
  ".orca-df-scope .mom-pin-group-text:hover {",
  "  opacity: 1;",
  "  border-color: color-mix(in srgb, var(--df-brand, #007AFF) 45%, transparent);",
  "  background: color-mix(in srgb, var(--df-brand, #007AFF) 12%, var(--orca-color-bg-1, #fff));",
  "}",
  ".orca-df-scope .mom-pin-ico {",
  "  display: inline-flex;",
  "  flex-shrink: 0;",
  "  color: var(--df-brand, #007AFF);",
  "}",
  ".orca-df-scope .mom-pin-title {",
  "  min-width: 0;",
  "  font-size: 13px;",
  "  font-weight: 500;",
  "  line-height: 1.2;",
  "  white-space: nowrap;",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "}",
  ".orca-df-scope .mom-pin-group-media {",
  "  display: grid;",
  "  gap: 2px;",
  "  padding: 3px;",
  "  border-radius: 8px;",
  "  border: 1px solid color-mix(in srgb, var(--df-brand, #007AFF) 22%, transparent);",
  "  background: color-mix(in srgb, var(--df-brand, #007AFF) 8%, var(--orca-color-bg-1, #fff));",
  "}",
  ".orca-df-scope .mom-pin-group-media .mom-pin-thumb img {",
  "  width: 28px;",
  "  height: 28px;",
  "  border-radius: 4px;",
  "}",
  ".orca-df-scope .mom-pin-group-media .mom-pin-thumb-single img {",
  "  width: 40px;",
  "  height: 40px;",
  "}",
  ".orca-df-scope .mom-pin-thumb-more {",
  "  font-size: 11px;",
  "}",
  ".orca-df-scope .mom-avatar,",
  ".orca-df-scope .mom-avatar-ph {",
  "  border-radius: var(--df-radius-md);",
  "}",
  ".orca-df-scope .north-luna-moments-item-name {",
  "  font-weight: 600;",
  "  letter-spacing: -0.02em;",
  "}",
  "/* ---- Controls ---- */",
  ".orca-df-scope button,",
  ".orca-df-scope input,",
  ".orca-df-scope textarea,",
  ".orca-df-scope select {",
  "  font-family: inherit;",
  "}",
  ".orca-df-scope .mom-publish-submit,",
  ".orca-df-scope .mom-empty-btn,",
  ".orca-df-scope .mom-btn-primary {",
  "  height: 34px;",
  "  min-width: 72px;",
  "  padding: 0 16px;",
  "  border: none;",
  "  border-radius: var(--df-radius-pill);",
  "  background: var(--df-brand);",
  "  color: var(--df-brand-fg);",
  "  font-size: 15px;",
  "  font-weight: 600;",
  "  letter-spacing: -0.01em;",
  "  line-height: 1;",
  "  box-shadow: none;",
  "  transition: opacity .15s ease, transform .15s ease, background .15s ease;",
  "}",
  ".orca-df-scope .mom-publish-submit:hover,",
  ".orca-df-scope .mom-empty-btn:hover,",
  ".orca-df-scope .mom-btn-primary:hover {",
  "  background: var(--df-brand-hover);",
  "  opacity: 0.96;",
  "}",
  ".orca-df-scope .mom-publish-submit:active,",
  ".orca-df-scope .mom-empty-btn:active,",
  ".orca-df-scope .mom-btn-primary:active {",
  "  background: var(--df-brand-pressed);",
  "  opacity: 0.88;",
  "}",
  ".orca-df-scope .mom-publish-inp,",
  ".orca-df-scope .mom-publish-textarea {",
  "  border: none;",
  "  border-radius: var(--df-radius-md);",
  "  background: var(--df-fill-tertiary);",
  "  transition: background .15s ease, box-shadow .15s ease;",
  "}",
  ".orca-df-scope .mom-publish-inp:hover,",
  ".orca-df-scope .mom-publish-textarea:hover {",
  "  background: color-mix(in srgb, var(--df-fill-tertiary) 85%, var(--df-brand) 15%);",
  "}",
  ".orca-df-scope .mom-publish-inp:focus,",
  ".orca-df-scope .mom-publish-textarea:focus,",
  ".orca-df-scope .mom-publish-card--editor:focus-within {",
  "  outline: none;",
  "  box-shadow: 0 0 0 3px var(--df-brand-tint);",
  "  background: var(--b3-theme-surface);",
  "}",
  ".orca-df-scope .mom-publish-card {",
  "  background: var(--b3-theme-surface);",
  "  border: var(--df-stroke) solid var(--moments-card-border);",
  "  border-radius: var(--df-radius-lg);",
  "  box-shadow: var(--df-shadow-4);",
  "}",
  ".orca-df-scope .mom-publish-nav {",
  "  height: 52px;",
  "  border-bottom: var(--df-stroke) solid var(--moments-nav-border);",
  "  background: color-mix(in srgb, var(--b3-theme-surface) 72%, transparent);",
  "  backdrop-filter: saturate(180%) blur(20px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(20px);",
  "}",
  ".orca-df-scope .mom-publish-title {",
  "  font-size: 17px;",
  "  font-weight: 600;",
  "  letter-spacing: -0.02em;",
  "}",
  ".orca-df-scope .mom-publish-grid-add,",
  ".orca-df-scope .mom-publish-grid-prev {",
  "  border-radius: var(--df-radius-md);",
  "}",
  ".orca-df-scope .mom-fab-stack .mom-outline-fab,",
  ".orca-df-scope .mom-fab-stack .mom-tag-fab,",
  ".orca-df-scope .mom-fab,",
  ".orca-df-scope button.mom-outline-fab,",
  ".orca-df-scope button.mom-tag-fab {",
  "  width: 44px;",
  "  height: 44px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: color-mix(in srgb, var(--b3-theme-surface) 82%, transparent);",
  "  backdrop-filter: saturate(180%) blur(16px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(16px);",
  "  box-shadow: var(--df-shadow-8);",
  "  color: var(--df-brand);",
  "}",
  ".orca-df-scope .mom-fab-stack .mom-outline-fab:hover,",
  ".orca-df-scope .mom-fab-stack .mom-tag-fab:hover,",
  ".orca-df-scope .mom-fab:hover {",
  "  background: var(--b3-theme-surface);",
  "}",
  ".orca-df-scope .mom-tag-fab.is-on {",
  "  color: var(--df-brand-fg);",
  "  background: var(--df-brand);",
  "  border-color: transparent;",
  "}",
  ".orca-df-scope .mom-cover-default {",
  "  background:",
  "    linear-gradient(160deg, #5AC8FA 0%, #007AFF 48%, #5856D6 100%);",
  "}",
  ".orca-df-scope.orca-df-dark .mom-cover-default {",
  "  background:",
  "    linear-gradient(160deg, #64D2FF 0%, #0A84FF 45%, #5E5CE6 100%);",
  "}",
  ".orca-df-scope .mom-cover-actions .mom-cover-settings,",
  ".orca-df-scope .mom-cover-actions button {",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: rgba(255,255,255,.28);",
  "  backdrop-filter: saturate(180%) blur(16px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(16px);",
  "  color: #fff;",
  "}",
  "/* ---- Tags / chips ---- */",
  ".north-luna-moments-tags { display: flex; flex-wrap: wrap; gap: 6px 8px; margin-top: 10px; }",
  ".north-luna-moments-tag {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  color: var(--df-brand);",
  "  background: var(--df-brand-tint);",
  "  padding: 4px 10px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  cursor: pointer;",
  "  user-select: none;",
  "  transition: background .15s ease, opacity .15s ease;",
  "}",
  ".north-luna-moments-tag:hover { background: var(--df-brand-tint-2); }",
  ".mom-publish-info { flex-wrap: wrap; }",
  ".mom-publish-info .mom-publish-info-tags { flex: 1 1 100%; min-width: 0; margin-top: 4px; }",
  "/* ---- Empty ---- */",
  ".mom-empty { padding: 64px 28px 52px; text-align: center; }",
  ".mom-empty-ico { font-size: 48px; line-height: 1; margin-bottom: 14px; opacity: 0.9; }",
  ".mom-empty-title { font-size: 20px; font-weight: 700; letter-spacing: -0.03em; margin: 0 0 8px; color: var(--b3-theme-on-surface); }",
  ".mom-empty-sub { font-size: 15px; line-height: 1.5; margin: 0 0 6px; color: var(--b3-theme-on-surface-light); }",
  ".mom-empty-hint { font-size: 13px; line-height: 1.5; margin: 0 0 20px; color: var(--b3-theme-on-surface-light); opacity: 0.95; }",
  ".mom-empty-btn { margin-top: 4px; }",
  "/* ---- Tag bar / refs ---- */",
  ".orca-df-tagbar { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; padding: 10px 16px 0; width: 100%; box-sizing: border-box; }",
  ".orca-df-tagbar-label { font-size: 13px; color: var(--b3-theme-on-surface-light); margin-right: 2px; }",
  ".orca-df-tagchip {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 5px 12px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: var(--df-fill-tertiary);",
  "  color: var(--b3-theme-on-background);",
  "  cursor: pointer;",
  "}",
  ".orca-df-tagchip.is-on, .orca-df-tagchip:hover {",
  "  background: var(--df-brand-tint);",
  "  color: var(--df-brand);",
  "}",
  ".orca-df-refs { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 10px; }",
  ".orca-df-refchip {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 3px 10px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: var(--df-stroke) dashed var(--b3-border-color);",
  "  background: transparent;",
  "  color: var(--b3-theme-on-surface-light);",
  "  cursor: pointer;",
  "}",
  ".orca-df-refchip:hover { color: var(--df-brand); border-color: var(--df-brand); background: var(--df-brand-tint); }",
  ".orca-df-open-orca {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 5px 10px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: none;",
  "  background: transparent;",
  "  color: var(--df-brand);",
  "  font-weight: 600;",
  "  cursor: pointer;",
  "}",
  ".orca-df-open-orca:hover { background: var(--df-brand-tint); }",
  ".orca-df-loc-btn.is-on { color: var(--df-brand); }",
  ".orca-df-tag-btn.is-on { color: var(--df-brand); }",
  ".orca-df-actions-wrap,",
  ".orca-df-scope .north-luna-moments-item-actions {",
  "  position: relative;",
  "}",
  ".orca-df-scope .north-luna-moments-action-bar {",
  "  display: flex;",
  "  align-items: center;",
  "  gap: 2px;",
  "  justify-content: flex-start;",
  "  flex-wrap: nowrap;",
  "}",
  ".orca-df-scope .north-luna-moments-action-btn {",
  "  width: 34px;",
  "  height: 34px;",
  "  border-radius: var(--df-radius-pill);",
  "}",
  ".orca-df-more-inline {",
  "  display: none;",
  "  align-items: center;",
  "  gap: 2px;",
  "  margin-left: 2px;",
  "  padding-left: 4px;",
  "  border-left: var(--df-stroke) solid color-mix(in srgb, var(--b3-border-color) 80%, transparent);",
  "  animation: orca-df-more-in .16s ease;",
  "}",
  ".north-luna-moments-action-bar.is-more-open .orca-df-more-inline,",
  ".mom-action-bar.is-more-open .orca-df-more-inline {",
  "  display: inline-flex;",
  "}",
  ".north-luna-moments-action-bar.is-more-open .orca-df-more-btn,",
  ".mom-action-bar.is-more-open .orca-df-more-btn {",
  "  color: var(--df-brand);",
  "  background: var(--df-brand-tint);",
  "}",
  ".orca-df-more-inline .orca-df-more-del {",
  "  color: #FF3B30;",
  "}",
  ".orca-df-more-inline .orca-df-more-del:hover {",
  "  background: rgba(255,59,48,.1);",
  "}",
  "@keyframes orca-df-more-in {",
  "  from { opacity: 0; transform: translateX(-4px); }",
  "  to { opacity: 1; transform: translateX(0); }",
  "}",
  ".orca-df-tags-list {",
  "  display: flex;",
  "  flex-wrap: wrap;",
  "  gap: 8px;",
  "  max-height: 220px;",
  "  overflow-y: auto;",
  "  margin-bottom: 12px;",
  "}",
  ".orca-df-tags-empty {",
  "  font-size: 13px;",
  "  color: var(--b3-theme-on-surface-light);",
  "  padding: 8px 0;",
  "}",
  ".orca-df-tagpick {",
  "  font-size: 13px;",
  "  line-height: 1.4;",
  "  padding: 4px 12px;",
  "  border-radius: var(--df-radius-pill);",
  "  border: var(--df-stroke) solid var(--b3-border-color);",
  "  background: var(--df-fill-tertiary);",
  "  color: var(--b3-theme-on-background);",
  "  cursor: pointer;",
  "}",
  ".orca-df-tagpick.is-on {",
  "  background: var(--df-brand-tint);",
  "  color: var(--df-brand);",
  "  border-color: var(--df-brand);",
  "}",
  ".orca-df-tags-add {",
  "  display: flex;",
  "  gap: 8px;",
  "  align-items: center;",
  "  margin-bottom: 8px;",
  "}",
  ".orca-df-tags-add .mom-inp { flex: 1 1 auto; min-width: 0; }",
  ".orca-df-loc-meta {",
  "  cursor: pointer;",
  "  color: var(--b3-theme-on-surface-light);",
  "}",
  ".orca-df-loc-meta:hover { color: var(--df-brand); }",
  ".orca-df-loc-pin { font-size: 12px; }",
  ".mom-publish-orca {",
  "  flex: none;",
  "  height: 34px;",
  "  padding: 0 14px;",
  "  margin-right: 0;",
  "  border: none;",
  "  border-radius: var(--df-radius-pill);",
  "  background: var(--df-fill-tertiary);",
  "  color: var(--df-brand);",
  "  font-size: 13px;",
  "  font-weight: 600;",
  "  cursor: pointer;",
  "}",
  ".mom-publish-orca:hover {",
  "  background: var(--df-brand-tint);",
  "}",
  ".mom-publish-nav-right { display: flex; align-items: center; gap: 8px; margin-left: auto; position: relative; z-index: 2; }",
  ".mom-publish-nav .mom-publish-back { position: relative; z-index: 2; border-radius: var(--df-radius-pill); color: var(--df-brand); }",
  ".mom-publish-nav .mom-publish-title { pointer-events: none; z-index: 0; }",
  "/* ---- Cover actions ---- */",
  ".mom-cover-actions {",
  "  position: absolute;",
  "  top: 14px;",
  "  right: 14px;",
  "  z-index: 12;",
  "  display: flex;",
  "  align-items: center;",
  "  gap: 8px;",
  "}",
  ".mom-cover-actions .mom-cover-settings {",
  "  position: static;",
  "  top: auto;",
  "  right: auto;",
  "}",
  ".mom-cover-signature {",
  "  position: absolute;",
  "  left: 16px;",
  "  right: 120px;",
  "  bottom: 22px;",
  "  z-index: 11;",
  "  margin: 0;",
  "  font-size: 15px;",
  "  line-height: 1.45;",
  "  font-weight: 500;",
  "  letter-spacing: 0.06em;",
  "  color: #fff;",
  "  text-shadow: 0 1px 2px rgba(0,0,0,.5), 0 2px 12px rgba(0,0,0,.35);",
  "  pointer-events: none;",
  "  white-space: nowrap;",
  "  overflow: hidden;",
  "  text-overflow: ellipsis;",
  "}",
  ".north-luna-moments-image-grid.nine {",
  "  grid-template-columns: repeat(3, 1fr);",
  "  max-width: 300px;",
  "}",
  ".north-luna-moments-grid-more {",
  "  position: relative;",
  "  display: block;",
  "  overflow: hidden;",
  "  border-radius: inherit;",
  "  cursor: pointer;",
  "}",
  ".north-luna-moments-grid-more .north-luna-moments-grid-img,",
  ".north-luna-moments-grid-more .north-luna-moments-grid-video-el {",
  "  width: 100%;",
  "  height: 100%;",
  "  object-fit: cover;",
  "  display: block;",
  "}",
  ".north-luna-moments-grid-more-badge {",
  "  position: absolute;",
  "  inset: 0;",
  "  display: flex;",
  "  align-items: center;",
  "  justify-content: center;",
  "  background: rgba(0,0,0,.46);",
  "  color: #fff;",
  "  font-size: 22px;",
  "  font-weight: 600;",
  "  letter-spacing: 0.02em;",
  "  pointer-events: none;",
  "  text-shadow: 0 1px 2px rgba(0,0,0,.35);",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ul,",
  ".north-luna-moments-item-text .orca-df-md-ol {",
  "  margin: 4px 0 6px;",
  "  padding-left: 1.4em;",
  "  list-style-position: outside;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ul {",
  "  list-style-type: disc !important;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ol {",
  "  list-style-type: decimal !important;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-ul .orca-df-md-ul { list-style-type: circle !important; }",
  ".north-luna-moments-item-text .orca-df-md-ul .orca-df-md-ul .orca-df-md-ul { list-style-type: square !important; }",
  ".north-luna-moments-item-text .orca-df-md-li {",
  "  margin: 2px 0;",
  "  line-height: 1.55;",
  "  display: list-item !important;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-p {",
  "  margin: 0 0 4px;",
  "  line-height: 1.55;",
  "  white-space: pre-wrap;",
  "  word-break: break-word;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-gap { height: 8px; }",
  ".north-luna-moments-item-text .orca-df-md-h {",
  "  font-weight: 650;",
  "  margin: 6px 0 4px;",
  "  line-height: 1.4;",
  "}",
  ".north-luna-moments-item-text .orca-df-md-h1 { font-size: 1.2em; }",
  ".north-luna-moments-item-text .orca-df-md-h2 { font-size: 1.1em; }",
  ".north-luna-moments-item-text .orca-df-md-h3 { font-size: 1.05em; }",
  ".north-luna-moments-item-text .orca-df-md-quote {",
  "  margin: 4px 0;",
  "  padding: 2px 0 2px 10px;",
  "  border-left: 3px solid var(--b3-border-color);",
  "  color: var(--b3-theme-on-surface-light);",
  "}",
  ".north-luna-moments-item-text .orca-df-md-code {",
  "  margin: 6px 0;",
  "  padding: 8px 10px;",
  "  border-radius: 8px;",
  "  background: var(--df-fill-tertiary);",
  "  overflow: auto;",
  "  font-size: 13px;",
  "  line-height: 1.45;",
  "}",
  "/* ---- Popover ---- */",
  ".orca-df-tag-popover {",
  "  position: fixed;",
  "  z-index: 2147483001;",
  "  min-width: 180px;",
  "  max-width: min(280px, calc(100vw - 24px));",
  "  max-height: min(360px, 50vh);",
  "  overflow: auto;",
  "  padding: 6px;",
  "  border-radius: var(--df-radius-lg);",
  "  background: color-mix(in srgb, var(--b3-theme-surface) 86%, transparent);",
  "  border: var(--df-stroke) solid var(--moments-card-border);",
  "  box-shadow: var(--df-shadow-16);",
  "  backdrop-filter: saturate(180%) blur(24px);",
  "  -webkit-backdrop-filter: saturate(180%) blur(24px);",
  "  box-sizing: border-box;",
  "}",
  ".orca-df-tag-popover-title {",
  "  font-size: 12px;",
  "  font-weight: 600;",
  "  color: var(--b3-theme-on-surface-light);",
  "  padding: 8px 10px 6px;",
  "  text-transform: uppercase;",
  "  letter-spacing: 0.04em;",
  "}",
  ".orca-df-tag-popover-item {",
  "  display: block;",
  "  width: 100%;",
  "  text-align: left;",
  "  border: none;",
  "  background: transparent;",
  "  color: var(--b3-theme-on-background);",
  "  font-size: 15px;",
  "  line-height: 1.35;",
  "  padding: 10px 12px;",
  "  border-radius: var(--df-radius-md);",
  "  cursor: pointer;",
  "}",
  ".orca-df-tag-popover-item:hover,",
  ".orca-df-tag-popover-item.is-on {",
  "  background: var(--df-brand-tint);",
  "  color: var(--df-brand);",
  "}",
  ".orca-df-tag-popover-empty {",
  "  font-size: 13px;",
  "  color: var(--b3-theme-on-surface-light);",
  "  padding: 12px 10px;",
  "}",
  "/* ---- Motion ---- */",
  "@media (prefers-reduced-motion: no-preference) {",
  "  .orca-df-scope .mom-item,",
  "  .orca-df-scope .north-luna-moments-item,",
  "  .orca-df-scope .mom-publish-submit,",
  "  .orca-df-scope .orca-df-tagchip,",
  "  .orca-df-scope .mom-outline-fab,",
  "  .orca-df-scope .mom-tag-fab {",
  "    transition: background .18s cubic-bezier(.22,.61,.36,1), border-color .18s ease, box-shadow .18s ease, color .18s ease, transform .18s cubic-bezier(.22,.61,.36,1), opacity .15s ease;",
  "  }",
  "  .orca-df-scope .mom-outline-fab:active,",
  "  .orca-df-scope .mom-tag-fab:active,",
  "  .orca-df-scope .mom-publish-submit:active {",
  "    transform: scale(0.96);",
  "  }",
  "}",
  "/* ---- 正文观感仍对齐虎鲸字号变量 ---- */",
  ".orca-df-scope {",
  "  --moments-text: var(--orca-color-text-1, var(--b3-theme-on-background, #000));",
  "  --df-body-font: var(--orca-fontfamily-ui, var(--orca-font-family, var(--df-font)));",
  "  --df-body-size: var(--orca-fontsize, 15px);",
  "  --df-body-leading: var(--orca-block-line-height, var(--orca-lineheight-md, 1.47));",
  "}",
  ".orca-df-scope .north-luna-moments-item-text,",
  ".orca-df-scope .mom-publish-textarea,",
  ".orca-df-scope .mom-publish-card--editor .mom-publish-textarea {",
  "  font-family: var(--df-body-font);",
  "  font-size: var(--df-body-size);",
  "  line-height: var(--df-body-leading);",
  "  color: var(--moments-text);",
  "  letter-spacing: -0.01em;",
  "  font-weight: 400;",
  "}",
  ".orca-df-scope .north-luna-moments-no-text {",
  "  color: var(--orca-color-text-3, var(--b3-theme-on-surface-light, #8E8E93));",
  "  font-size: var(--df-body-size);",
  "  line-height: var(--df-body-leading);",
  "}",
  ".orca-df-scope .mom-inline-code,",
  ".orca-df-scope .north-luna-moments-item-text code {",
  "  font-family: var(--orca-fontfamily-code, var(--df-font-mono));",
  "  font-size: 0.92em;",
  "  line-height: inherit;",
  "  background: var(--df-fill-tertiary);",
  "  border-radius: 4px;",
  "  padding: 0.1em 0.35em;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text a,",
  ".orca-df-scope .north-luna-moments-item-text .mom-md-link {",
  "  color: var(--orca-color-primary-5, var(--df-brand));",
  "}",
  "/* ---- 卡片正文层级：正文 > 列表 > meta 日期 ---- */",
  ".orca-df-scope .mom-item,",
  ".orca-df-scope .north-luna-moments-item {",
  "  padding: 12px 14px 10px;",
  "}",
  ".orca-df-scope .north-luna-moments-item-header {",
  "  margin-bottom: 6px;",
  "  gap: 8px;",
  "}",
  ".orca-df-scope .north-luna-moments-item-header .mom-avatar,",
  ".orca-df-scope .north-luna-moments-item-header .mom-avatar-ph {",
  "  width: 34px;",
  "  height: 34px;",
  "  font-size: 14px;",
  "}",
  ".orca-df-scope .north-luna-moments-item-name {",
  "  font-size: 14px;",
  "  font-weight: 600;",
  "  color: var(--orca-color-text-2, var(--b3-theme-on-surface, #3A3A3C));",
  "}",
  ".orca-df-scope .north-luna-moments-item-text {",
  "  margin-bottom: 2px;",
  "  line-height: 1.55;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text > .orca-df-md-p:first-child {",
  "  color: var(--moments-text);",
  "  font-weight: 450;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-ul,",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-ol {",
  "  margin: 6px 0 2px;",
  "  color: color-mix(in srgb, var(--moments-text) 86%, transparent);",
  "  font-size: 0.96em;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-li {",
  "  line-height: 1.5;",
  "  margin: 1px 0;",
  "}",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-p + .orca-df-md-ul,",
  ".orca-df-scope .north-luna-moments-item-text .orca-df-md-p + .orca-df-md-ol {",
  "  margin-top: 4px;",
  "}",
  ".orca-df-scope .north-luna-moments-tags {",
  "  margin-top: 6px;",
  "  margin-bottom: 0;",
  "}",
  ".orca-df-scope .north-luna-moments-item-meta {",
  "  margin-top: 8px;",
  "  margin-bottom: 0;",
  "}",
  ".orca-df-scope .north-luna-moments-meta-item {",
  "  font-size: 11px;",
  "  line-height: 1.35;",
  "  letter-spacing: 0.01em;",
  "  color: var(--orca-color-text-3, var(--b3-theme-on-surface-light, #8E8E93));",
  "  opacity: 0.92;",
  "}",
  ".orca-df-scope .north-luna-moments-meta-item + .north-luna-moments-meta-item::before {",
  "  margin: 0 6px;",
  "  opacity: 0.35;",
  "  font-weight: 500;",
  "}",
  ".orca-df-scope .north-luna-moments-item-actions {",
  "  margin-top: 4px;",
  "}",
  ".orca-df-scope .north-luna-moments-comment-panel {",
  "  margin-top: 6px;",
  "}",
  ".orca-df-scope .orca-df-inline-ref {",
  "  display: inline;",
  "  text-decoration: none;",
  "  border-bottom: 1px dashed color-mix(in srgb, var(--df-brand, #007AFF) 55%, transparent);",
  "  cursor: pointer;",
  "}",
  ".orca-df-scope .orca-df-inline-ref:hover {",
  "  border-bottom-style: solid;",
  "}",
  ".orca-df-refresh-fab svg { display: block; }",
  ".orca-df-time-hint {",
  "  margin: 10px 0 0;",
  "  font-size: 12px;",
  "  line-height: 1.4;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-scope .north-luna-moments-item-text,",
  ".orca-df-scope .mom-item-text {",
  "  cursor: pointer;",
  "}",
  ".orca-df-load-more {",
  "  display: flex;",
  "  justify-content: center;",
  "  padding: 16px 12px 28px;",
  "}",
  ".orca-df-load-more-btn {",
  "  appearance: none;",
  "  border: 1px solid color-mix(in srgb, var(--orca-color-text-3, #8e8e93) 35%, transparent);",
  "  background: color-mix(in srgb, var(--orca-color-bg-1, #fff) 92%, transparent);",
  "  color: var(--orca-color-text-2, #636366);",
  "  border-radius: 999px;",
  "  padding: 8px 18px;",
  "  font-size: 13px;",
  "  line-height: 1.3;",
  "  cursor: pointer;",
  "}",
  ".orca-df-load-more-btn:hover {",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "  border-color: color-mix(in srgb, var(--df-brand, #007AFF) 45%, transparent);",
  "}",
  /* 回收站（借鉴 orca-plugin-pizhu，独立 class 避免冲突） */
  ".orca-df-trash-fab { position: relative; }",
  ".orca-df-trash-fab-count,",
  ".orca-df-archive-fab-count,",
  ".orca-df-tools-fab-count {",
  "  position: absolute; top: -4px; right: -4px;",
  "  min-width: 16px; height: 16px; padding: 0 4px;",
  "  border-radius: 999px; background: var(--orca-color-accent, #0F6CBD);",
  "  color: #fff; font-size: 10px; font-weight: 600; line-height: 16px; text-align: center;",
  "}",
  ".orca-df-tools-fab { position: relative; }",
  ".orca-df-trash-backdrop {",
  "  position: fixed; inset: 0; z-index: 2147482999;",
  "  display: flex; align-items: center; justify-content: center;",
  "  background: rgba(0, 0, 0, 0.30);",
  "}",
  ".orca-df-trash-pop {",
  "  z-index: 2147483000; width: 560px; max-width: calc(100vw - 48px); max-height: 76vh;",
  "  display: flex; flex-direction: column; padding: 20px 24px 24px;",
  "  border-radius: 10px; background: var(--orca-color-bg-1, #fff);",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.08));",
  "  box-shadow: var(--orca-shadow-modal, 0 32px 64px rgba(0,0,0,0.24));",
  "  font-size: 14px; line-height: 1.5;",
  "}",
  ".orca-df-trash-head {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  padding: 2px 0 14px; font-size: 18px; font-weight: 600;",
  "}",
  ".orca-df-trash-head-tools { display: flex; align-items: center; gap: 10px; }",
  ".orca-df-trash-hint { font-size: 12px; font-weight: 400; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-trash-close {",
  "  appearance: none; border: 0; background: transparent; cursor: pointer;",
  "  font-size: 22px; line-height: 1; color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-trash-body { overflow: auto; flex: 1 1 auto; min-height: 120px; }",
  ".orca-df-trash-empty { padding: 28px 8px; text-align: center; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-trash-row {",
  "  display: flex; align-items: center; justify-content: space-between; gap: 12px;",
  "  padding: 12px 4px; border-top: 1px solid var(--orca-color-border, rgba(0,0,0,0.06));",
  "}",
  ".orca-df-trash-meta { min-width: 0; flex: 1 1 auto; }",
  ".orca-df-trash-title {",
  "  font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;",
  "}",
  ".orca-df-trash-sub { margin-top: 2px; font-size: 12px; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-trash-actions { display: flex; gap: 8px; flex-shrink: 0; }",
  ".orca-df-trash-act {",
  "  appearance: none; border: 1px solid var(--orca-color-border, rgba(0,0,0,0.12));",
  "  background: transparent; border-radius: 6px; padding: 4px 10px; cursor: pointer;",
  "  color: var(--orca-color-text-2, #636366); font-size: 13px;",
  "}",
  ".orca-df-trash-act.danger { color: var(--orca-color-danger, #c42b1c); border-color: color-mix(in srgb, var(--orca-color-danger, #c42b1c) 35%, transparent); }",
  ".orca-df-trash-foot { padding-top: 14px; display: flex; justify-content: flex-end; }",
  /* 归档柜 */
  ".orca-df-archive-fab { position: relative; }",
  ".orca-df-archive-backdrop {",
  "  position: fixed; inset: 0; z-index: 2147482999;",
  "  display: flex; align-items: center; justify-content: center;",
  "  background: rgba(0, 0, 0, 0.30);",
  "}",
  ".orca-df-archive-pop {",
  "  z-index: 2147483000; width: 560px; max-width: calc(100vw - 48px); max-height: 76vh;",
  "  display: flex; flex-direction: column; padding: 20px 24px 24px;",
  "  border-radius: 10px; background: var(--orca-color-bg-1, #fff);",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.08));",
  "  box-shadow: var(--orca-shadow-modal, 0 32px 64px rgba(0,0,0,0.24));",
  "  font-size: 14px; line-height: 1.5;",
  "}",
  ".orca-df-archive-head {",
  "  display: flex; align-items: center; justify-content: space-between;",
  "  padding: 2px 0 14px; font-size: 18px; font-weight: 600;",
  "}",
  ".orca-df-archive-head-tools { display: flex; align-items: center; gap: 10px; }",
  ".orca-df-archive-hint { font-size: 12px; font-weight: 400; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-archive-close {",
  "  appearance: none; border: 0; background: transparent; cursor: pointer;",
  "  font-size: 22px; line-height: 1; color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-archive-body { overflow: auto; flex: 1 1 auto; min-height: 120px; }",
  ".orca-df-archive-empty { padding: 28px 8px; text-align: center; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-archive-row {",
  "  display: flex; align-items: center; justify-content: space-between; gap: 12px;",
  "  padding: 12px 4px; border-top: 1px solid var(--orca-color-border, rgba(0,0,0,0.06));",
  "}",
  ".orca-df-archive-meta { min-width: 0; flex: 1 1 auto; }",
  ".orca-df-archive-title {",
  "  font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;",
  "}",
  ".orca-df-archive-sub { margin-top: 2px; font-size: 12px; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-archive-actions { display: flex; gap: 8px; flex-shrink: 0; }",
  ".orca-df-archive-act {",
  "  appearance: none; border: 1px solid var(--orca-color-border, rgba(0,0,0,0.12));",
  "  background: transparent; border-radius: 6px; padding: 4px 10px; cursor: pointer;",
  "  color: var(--orca-color-text-2, #636366); font-size: 13px;",
  "}",
  /* 月份大纲（对齐安卓 OutlineScreen：年份 chip + 分月卡片） */
  ".orca-df-outline-backdrop {",
  "  position: fixed; inset: 0; z-index: 2147482999;",
  "  display: flex; align-items: stretch; justify-content: center;",
  "  background: rgba(0, 0, 0, 0.28);",
  "}",
  ".orca-df-outline-pop {",
  "  z-index: 2147483000; width: min(420px, 100vw); max-width: 100vw;",
  "  max-height: min(92vh, 900px); margin: auto 0;",
  "  display: flex; flex-direction: column;",
  "  background: var(--orca-color-bg-1, #fff);",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "  border-radius: 12px 12px 0 0;",
  "  box-shadow: var(--orca-shadow-modal, 0 24px 48px rgba(0,0,0,0.22));",
  "  overflow: hidden;",
  "}",
  "@media (min-width: 720px) {",
  "  .orca-df-outline-pop {",
  "    width: min(480px, calc(100vw - 48px)); max-height: 82vh; margin: auto;",
  "    border-radius: 12px;",
  "  }",
  "}",
  ".orca-df-outline-head {",
  "  display: flex; align-items: center; gap: 4px;",
  "  padding: 10px 12px 8px; font-size: 17px; font-weight: 600;",
  "  border-bottom: 1px solid var(--orca-color-border, rgba(0,0,0,0.06));",
  "}",
  ".orca-df-outline-back {",
  "  appearance: none; border: 0; background: transparent; cursor: pointer;",
  "  width: 36px; height: 36px; border-radius: 10px;",
  "  display: inline-flex; align-items: center; justify-content: center;",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "}",
  ".orca-df-outline-back:hover { background: color-mix(in srgb, var(--df-brand, #007AFF) 10%, transparent); }",
  ".orca-df-outline-head-spacer { width: 36px; }",
  ".orca-df-outline-years { padding: 12px 16px 0; display: flex; flex-direction: column; gap: 6px; }",
  ".orca-df-outline-year-row { display: flex; gap: 6px; }",
  ".orca-df-outline-year,",
  ".orca-df-outline-year-ph {",
  "  flex: 1 1 0; min-width: 0; height: 40px;",
  "}",
  ".orca-df-outline-year {",
  "  appearance: none; cursor: pointer;",
  "  border-radius: 10px; font-size: 13px; font-weight: 600;",
  "  border: 1px solid color-mix(in srgb, var(--df-brand, #007AFF) 40%, transparent);",
  "  background: color-mix(in srgb, var(--df-brand, #007AFF) 10%, transparent);",
  "  color: var(--df-brand, #007AFF);",
  "}",
  ".orca-df-outline-year.is-on {",
  "  background: var(--df-brand, #007AFF);",
  "  border-color: color-mix(in srgb, var(--df-brand, #007AFF) 85%, transparent);",
  "  color: #fff;",
  "}",
  ".orca-df-outline-hint {",
  "  padding: 6px 16px 8px; font-size: 12px;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-outline-months {",
  "  flex: 1 1 auto; min-height: 120px; overflow: auto;",
  "  padding: 4px 16px 16px;",
  "  display: grid; grid-template-columns: 1fr 1fr; gap: 6px; align-content: start;",
  "}",
  ".orca-df-outline-month {",
  "  appearance: none; cursor: pointer; height: 40px; padding: 0 8px;",
  "  display: flex; align-items: center; gap: 6px; min-width: 0;",
  "  border-radius: 10px;",
  "  border: 1px solid color-mix(in srgb, var(--df-brand, #007AFF) 40%, transparent);",
  "  background: color-mix(in srgb, var(--df-brand, #007AFF) 10%, transparent);",
  "  color: var(--df-brand, #007AFF);",
  "  font-size: 13px; font-weight: 600;",
  "}",
  ".orca-df-outline-month:hover {",
  "  border-color: color-mix(in srgb, var(--df-brand, #007AFF) 85%, transparent);",
  "}",
  ".orca-df-outline-cal { flex-shrink: 0; opacity: 0.95; }",
  ".orca-df-outline-month-label {",
  "  flex: 1 1 auto; min-width: 0;",
  "  white-space: nowrap; overflow: hidden; text-overflow: ellipsis; text-align: left;",
  "}",
  ".orca-df-outline-month-count {",
  "  flex-shrink: 0; font-size: 12px; font-weight: 500;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-outline-empty {",
  "  grid-column: 1 / -1; padding: 24px 8px; text-align: center;",
  "  color: var(--orca-color-text-3, #8e8e93); font-size: 14px; font-weight: 400;",
  "}",
  /* 热力图：上下半年两行；弹层强制加宽，格子固定尺寸（约原 1.5 倍） */
  ".orca-df-scope .mom-calendar-content {",
  "  max-width: min(680px, 96vw) !important;",
  "}",
  ".orca-df-scope .mom-calendar-content:has(.mom-calendar-heat-wrap) {",
  "  width: min(680px, 96vw) !important;",
  "}",
  ".orca-df-scope .mom-calendar-heat-wrap {",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 20px;",
  "  padding: 8px 8px 12px;",
  "  width: 100%;",
  "  box-sizing: border-box;",
  "}",
  ".orca-df-scope .mom-calendar-heat-half {",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 8px;",
  "  padding-bottom: 14px;",
  "  border-bottom: 1px solid color-mix(in srgb, var(--orca-color-border, rgba(0,0,0,0.08)) 80%, transparent);",
  "}",
  ".orca-df-scope .mom-calendar-heat-half:last-child {",
  "  border-bottom: none;",
  "  padding-bottom: 0;",
  "}",
  ".orca-df-scope .mom-calendar-heat-caption {",
  "  font-size: 13px;",
  "  font-weight: 500;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-scope .mom-calendar-heat-empty {",
  "  font-size: 14px;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "  padding: 16px 0;",
  "}",
  ".orca-df-scope .mom-calendar-heat-wrap .mom-calendar-columns {",
  "  display: flex;",
  "  gap: 4px;",
  "  width: 100%;",
  "  justify-content: space-between;",
  "}",
  ".orca-df-scope .mom-calendar-heat-wrap .mom-calendar-column {",
  "  flex: 1 1 0;",
  "  min-width: 12px;",
  "  max-width: 18px;",
  "  display: flex;",
  "  flex-direction: column;",
  "  gap: 4px;",
  "}",
  ".orca-df-scope .mom-calendar-heat-wrap .mom-calendar-cell {",
  "  width: 100%;",
  "  min-width: 12px;",
  "  min-height: 12px;",
  "  aspect-ratio: 1;",
  "  border-radius: 4px;",
  "  background-color: #EBEDF0;",
  "  transition: transform .12s ease;",
  "  cursor: default;",
  "  box-shadow: none;",
  "}",
  ".orca-df-scope .mom-calendar-cell[data-date] { cursor: pointer; }",
  ".orca-df-scope .mom-calendar-heat-wrap .mom-calendar-cell:hover {",
  "  transform: scale(1.18);",
  "  box-shadow: none;",
  "  outline: 1px solid color-mix(in srgb, var(--df-brand, #007AFF) 55%, transparent);",
  "  outline-offset: 0;",
  "  z-index: 1;",
  "}",
  ".orca-df-scope .mom-calendar-cell.level-empty {",
  "  background-color: transparent;",
  "  opacity: 0;",
  "  pointer-events: none;",
  "}",
  ".orca-df-scope .mom-calendar-cell.level-empty:hover {",
  "  transform: none;",
  "  outline: none;",
  "}",
  ".orca-df-scope .mom-calendar-cell.level-0 { background-color: #EBEDF0; }",
  ".orca-df-scope .mom-calendar-cell.level-1 { background-color: #B6E3FF; }",
  ".orca-df-scope .mom-calendar-cell.level-2 { background-color: #54AEFF; }",
  ".orca-df-scope .mom-calendar-cell.level-3 { background-color: #218BFF; }",
  ".orca-df-scope .mom-calendar-cell.level-4 { background-color: #0550AE; }",
  ".orca-df-scope .mom-calendar-heat-wrap .mom-calendar-months {",
  "  position: relative;",
  "  margin-top: 6px;",
  "  height: 20px;",
  "  min-width: 0;",
  "  width: 100%;",
  "}",
  ".orca-df-scope .mom-calendar-heat-wrap .mom-calendar-month-label {",
  "  position: absolute;",
  "  transform: translateX(-50%);",
  "  font-size: 13px;",
  "  color: var(--orca-color-text-3, #8e8e93);",
  "  white-space: nowrap;",
  "}",
  "/* ---- Tools / stats / export / images / layout ---- */",
  ".orca-df-quickbar { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; padding: 8px 16px 0; width: 100%; box-sizing: border-box; }",
  ".orca-df-quick-kw { font-size: 12px; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-scope .mom-fab-stack .orca-df-search-fab.is-on,",
  ".orca-df-scope .mom-fab-stack .orca-df-tools-fab.is-on {",
  "  color: var(--df-brand-fg);",
  "  background: var(--df-brand);",
  "  border-color: transparent;",
  "}",
  ".orca-df-layout-compact .mom-cover { height: clamp(110px, 16vh, 180px); }",
  ".orca-df-layout-compact .mom-list, .orca-df-layout-compact .north-luna-moments-list { padding-left: 12px; padding-right: 12px; }",
  ".orca-df-layout-tall .mom-cover { height: clamp(220px, 34vh, 380px); }",
  ".orca-df-tools-backdrop, .orca-df-images-backdrop {",
  "  position: fixed; inset: 0; z-index: 2147482999;",
  "  display: flex; align-items: center; justify-content: center;",
  "  background: rgba(0, 0, 0, 0.30);",
  "}",
  ".orca-df-tools-pop {",
  "  z-index: 2147483000; width: 440px; max-width: calc(100vw - 48px); max-height: 80vh;",
  "  display: flex; flex-direction: column; padding: 20px 24px 24px;",
  "  border-radius: 10px; background: var(--orca-color-bg-1, #fff);",
  "  color: var(--orca-color-text-1, #1c1c1e);",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.08));",
  "  box-shadow: var(--orca-shadow-modal, 0 32px 64px rgba(0,0,0,0.24));",
  "  font-size: 14px; line-height: 1.5;",
  "}",
  ".orca-df-tools-wide { width: 560px; }",
  ".orca-df-tools-head {",
  "  display: flex; align-items: center; justify-content: space-between; gap: 12px;",
  "  padding: 2px 0 14px; font-size: 18px; font-weight: 600;",
  "}",
  ".orca-df-tools-head-tools { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }",
  ".orca-df-tools-close {",
  "  appearance: none; border: 0; background: transparent; cursor: pointer;",
  "  font-size: 22px; line-height: 1; color: var(--orca-color-text-3, #8e8e93);",
  "}",
  ".orca-df-tools-body { overflow: auto; flex: 1 1 auto; min-height: 80px; display: flex; flex-direction: column; gap: 10px; }",
  ".orca-df-tools-muted { font-size: 13px; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-tools-label { font-size: 13px; font-weight: 500; }",
  ".orca-df-tools-input {",
  "  width: 100%; box-sizing: border-box; padding: 10px 12px; border-radius: 8px;",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.12));",
  "  background: var(--orca-color-bg-2, #f5f5f7); color: inherit; font-size: 14px;",
  "}",
  ".orca-df-tools-tile {",
  "  appearance: none; text-align: left; cursor: pointer;",
  "  display: flex; flex-direction: column; gap: 4px;",
  "  padding: 12px 14px; border-radius: 10px;",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.08));",
  "  background: var(--orca-color-bg-2, #f5f5f7); color: inherit;",
  "}",
  ".orca-df-tools-tile:hover { border-color: var(--df-brand, #007AFF); }",
  ".orca-df-tools-tile b { font-size: 15px; }",
  ".orca-df-tools-tile span { font-size: 12px; color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-tools-btn {",
  "  appearance: none; cursor: pointer; text-align: left;",
  "  padding: 10px 14px; border-radius: 8px;",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.12));",
  "  background: transparent; color: inherit; font-size: 14px;",
  "}",
  ".orca-df-tools-btn.primary, .orca-df-tools-btn.is-on {",
  "  background: var(--df-brand, #007AFF); color: #fff; border-color: transparent;",
  "}",
  ".orca-df-tools-mini {",
  "  appearance: none; cursor: pointer; padding: 4px 10px; border-radius: 6px;",
  "  border: 1px solid var(--orca-color-border, rgba(0,0,0,0.12));",
  "  background: transparent; color: var(--orca-color-text-2, #636366); font-size: 13px;",
  "}",
  ".orca-df-tools-mini:disabled { opacity: 0.4; cursor: default; }",
  ".orca-df-tools-actions { display: flex; flex-wrap: wrap; gap: 8px; }",
  ".orca-df-tools-status { font-size: 13px; color: var(--orca-color-text-2, #636366); }",
  ".orca-df-tools-sec { margin-top: 8px; }",
  ".orca-df-tools-sec-t { font-weight: 600; margin-bottom: 6px; }",
  ".orca-df-tools-row {",
  "  display: flex; justify-content: space-between; gap: 12px;",
  "  padding: 6px 0; border-top: 1px solid var(--orca-color-border, rgba(0,0,0,0.06));",
  "}",
  ".orca-df-stats-grid {",
  "  display: grid; grid-template-columns: repeat(4, minmax(0, 1fr)); gap: 8px;",
  "}",
  "@media (max-width: 520px) { .orca-df-stats-grid { grid-template-columns: repeat(2, minmax(0, 1fr)); } }",
  ".orca-df-stats-card {",
  "  padding: 12px 10px; border-radius: 10px;",
  "  background: var(--orca-color-bg-2, #f5f5f7); text-align: center;",
  "}",
  ".orca-df-stats-n { font-size: 22px; font-weight: 700; letter-spacing: -0.03em; }",
  ".orca-df-stats-l { font-size: 12px; color: var(--orca-color-text-3, #8e8e93); margin-top: 2px; }",
  ".orca-df-tools-entry {",
  "  display: flex; align-items: center; justify-content: space-between; gap: 12px;",
  "  padding: 10px 0; border-top: 1px solid var(--orca-color-border, rgba(0,0,0,0.06));",
  "}",
  ".orca-df-tools-entry-main { min-width: 0; flex: 1; }",
  ".orca-df-tools-entry-t { font-weight: 500; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }",
  ".orca-df-img-list { display: flex; flex-direction: column; gap: 8px; }",
  ".orca-df-img-row { display: flex; align-items: center; gap: 10px; }",
  ".orca-df-img-thumb { width: 56px; height: 56px; object-fit: cover; border-radius: 8px; background: #eee; flex-shrink: 0; }",
  ".orca-df-img-meta { flex: 1; min-width: 0; }",
  ".orca-df-img-acts { display: flex; gap: 4px; flex-shrink: 0; }",
  ".orca-df-img-progress { height: 4px; border-radius: 2px; background: var(--orca-color-bg-2, #eee); overflow: hidden; }",
  ".orca-df-img-progress-bar { height: 100%; background: var(--df-brand, #007AFF); transition: width .2s ease; }",
  ".orca-df-list-search {",
  "  min-width: 110px; flex: 1 1 auto; height: 26px; padding: 0 8px;",
  "  border-radius: 7px; border: 1px solid var(--orca-color-border, rgba(0,0,0,.12));",
  "  background: var(--orca-color-bg-2, rgba(120,120,128,.08)); color: inherit;",
  "  font: inherit; font-size: 13px; outline: none;",
  "}",
  ".orca-df-list-search::placeholder { color: var(--orca-color-text-3, #8e8e93); }",
  ".orca-df-list-more { display: flex; justify-content: center; padding: 10px 0; }",
  ".orca-df-archive-foot { display: flex; justify-content: flex-end; padding: 8px 0 0; }",
  ".orca-df-media-list { max-height: 46vh; overflow: auto; margin: 6px 0 10px; }",
  ".orca-df-search-quick { display: flex; flex-wrap: wrap; gap: 12px; padding: 2px 0 10px; }",
  ".orca-df-search-check { display: inline-flex; align-items: center; gap: 5px; font-size: 13px; }",
  ".orca-df-search-dates { display: flex; align-items: center; gap: 8px; padding: 0 0 10px; }",
  ".orca-df-list-sort { height: 26px; padding: 0 6px; border-radius: 7px; border: 1px solid var(--orca-color-border, rgba(0,0,0,.12)); background: var(--orca-color-bg-2, rgba(120,120,128,.08)); color: inherit; font: inherit; font-size: 13px; outline: none; }",
  "/* ---- 封面日历：照片模式两列（一屏显示两个月） ---- */",
  ".mom-calendar-photo-twocol { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 16px 22px; align-items: start; }",
  ".mom-calendar-photo-row { grid-template-columns: repeat(7, minmax(32px, 1fr)); }",
  ".mom-calendar-photo-cell { max-width: none; }",
  "@media (max-width: 720px) { .mom-calendar-photo-twocol { grid-template-columns: 1fr; } }",
  "/* ---- 快速撰写 / 心情天气 ---- */",
  ".orca-df-compose-modal { max-width: 520px; width: 92%; }",
  ".orca-df-compose-text { width: 100%; min-height: 84px; resize: vertical; box-sizing: border-box; }",
  ".orca-df-compose-imgs { display: flex; flex-wrap: wrap; gap: 8px; margin: 8px 0 0; }",
  ".orca-df-compose-img { position: relative; width: 64px; height: 64px; border-radius: 8px; overflow: hidden; background: var(--orca-color-bg-2, #eee); }",
  ".orca-df-compose-img img { width: 100%; height: 100%; object-fit: cover; display: block; }",
  ".orca-df-compose-img-x { position: absolute; top: 2px; right: 2px; width: 18px; height: 18px; border: 0; border-radius: 50%; background: rgba(0,0,0,.55); color: #fff; line-height: 1; cursor: pointer; }",
  ".orca-df-compose-row { display: flex; gap: 8px; align-items: center; margin-top: 8px; }",
  ".orca-df-compose-row .mom-inp { flex: 1 1 auto; min-width: 0; }",
  ".orca-df-compose-mood { flex: 0 0 92px; }",
  ".orca-df-compose-weather { flex: 0 0 96px; }",
  ".orca-df-meta-chips { display: flex; flex-wrap: wrap; gap: 6px; margin: 6px 0 2px; }",
  ".orca-df-meta-chip { font-size: 12px; padding: 1px 8px; border-radius: 980px; background: var(--orca-color-bg-2, rgba(120,120,128,.1)); color: var(--orca-color-text-2, #555); }",
  ".orca-df-img-row { cursor: grab; }",
  ".orca-df-img-row.is-dragging { opacity: .45; }"
].join("\n");
const allCss = css + extraCss;

const VERSION = "0.3.19";
const REPO_URL = "https://github.com/kx1356/orca-diaryflow";

// ---------- 组装输出 ----------
const orcaBlocks = readFileSync(join(ROOT, "src", "orca-blocks.js"), "utf8");
const entry = readFileSync(join(ROOT, "src", "orca-entry.js"), "utf8");

const out = [
  "// orca-diaryflow v" + VERSION + " — light compose + Orca blocks (plan C)",
  "// Orca Note adaptation: panel, plugin-file media, block store, tags/refs/search",
  header,
  blocks.storage,
  blocks.util,
  blocks.render,
  blocks.export,
  blocks.editor,
  "",
  "// ===== i18n (zh -> en) =====",
  readFileSync(join(ROOT, "src", "orca-i18n.js"), "utf8"),
  "",
  "// ===== Settings =====",
  readFileSync(join(ROOT, "src", "orca-settings.js"), "utf8"),
  "",
  "// ===== Orca blocks store =====",
  orcaBlocks,
  "",
  "// ===== Orca trash (soft-delete) =====",
  readFileSync(join(ROOT, "src", "orca-trash.js"), "utf8"),
  "",
  "// ===== Orca tools (stats/export/recap/search/layout/images) =====",
  readFileSync(join(ROOT, "src", "orca-tools.js"), "utf8"),
  "",
  "// ===== Orca Note entry =====",
  "var ORCA_CSS = " + JSON.stringify(allCss) + ";",
  "",
  entry
].join("\n");

mkdirSync(join(ROOT, "dist"), { recursive: true });
writeFileSync(join(ROOT, "dist", "index.js"), out);
// 集市图标：优先保留本地 icon-market.png（≤80）/ icon.png，勿被思源源图覆盖；SVG 单独保留
const marketIcon = join(ROOT, "icon-market.png");
if (existsSync(marketIcon)) {
  copyFileSync(marketIcon, join(ROOT, "icon.png"));
} else if (!existsSync(join(ROOT, "icon.png"))) {
  copyFileSync(SRC_ICON, join(ROOT, "icon.png"));
}

// plugin.json（mreader 同款格式；文件夹名仍为 orca-diaryflow）
const pluginMeta = {
  name: "orca-diaryflow",
  author: "kx1356",
  url: REPO_URL,
  version: VERSION,
  minAppVersion: "2.10.0",
  script: "index.js",
  description: {
    default: "Moments-style diary feed for Orca Note journals tagged #日记流",
    zh_CN: "日记流：朋友圈式时间线，深度编辑跳转虎鲸"
  },
  displayName: {
    default: "Diary Flow",
    zh_CN: "日记流"
  },
  icon: "icon.svg",
  backends: [],
  i18n: ["zh_CN", "en_US"]
};
writeFileSync(join(ROOT, "plugin.json"), JSON.stringify(pluginMeta, null, 4) + "\n");

// package.json（集市校验所需元数据）
const pkgMeta = {
  name: "orca-plugin-diaryflow",
  version: VERSION,
  type: "module",
  description:
    "Moments-style diary feed for Orca Note: timeline of #日记流 blocks, cover/avatar, tags, location, and deep edit in Orca journals.",
  author: "kx1356",
  license: "MIT",
  keywords: ["orca-note", "orca-plugin", "diary", "moments", "journal", "timeline"],
  repository: { type: "git", url: REPO_URL + ".git" },
  homepage: REPO_URL,
  bugs: { url: REPO_URL + "/issues" },
  private: false,
  scripts: {
    build: "node build.mjs",
    deploy: "node tools/deploy.mjs",
    "validate:marketplace": "node scripts/validate-marketplace-package.mjs"
  },
  orcaNoteMarketplace: {
    id: "orca-diaryflow",
    name: "Diary Flow",
    category: "Productivity",
    artifactName: "orca-diaryflow",
    translations: {
      zh: {
        name: "日记流",
        description:
          "朋友圈式日记时间流：标签与快捷筛选、归档柜、回收站、统计/导出/回顾、搜索与布局；新建与深度编辑跳转虎鲸日记页。",
        category: "效率工具"
      },
      en: {
        name: "Diary Flow",
        description:
          "Moments-style diary feed with filters, stats/export/recap, search, layout presets, archive and trash; deep edit in Orca journals.",
        category: "Productivity"
      }
    }
  },
  peerDependencies: {
    react: "^18.2.0",
    valtio: "^1.13.2"
  }
};
writeFileSync(join(ROOT, "package.json"), JSON.stringify(pkgMeta, null, 2) + "\n");

console.log("built dist/index.js:", out.length, "bytes");
console.log("dist ready at", join(ROOT, "dist", "index.js"));
